.travis.yml
Test against both 2.11.4 and 2.10.4.
=> Add more JVMs and Scalas to TravisCI

docs.md
This is for initial documentation, just a single section inserted into the otherwise unchanged document to make sure users know about the feature.
Should there be agreement that the applicative style should be documented as the preferred syntax in the future, more changes would be necessary to rewrite more of the existing reader examples in an applicative style and use the monadic style less often than in the current version of the docs.
=> document applicative syntax for request readers

core/src/main/scala/io/finch/route/package.scala, core/src/test/scala/io/finch/route/RouterSpec.scala
Realised that I missed an important part in routers. In case of two similar routes like `/users/:id` and `/users` it wasn't really clear how to chose the right router in `orElse` combinator. The previous implementation was always taking the first succeed router, which is wrong in the following case:
```scala
val r = (Get / "users" /> GetAllUsers) | (Get / "users" / int /> GetUser)
r("/users/10") // returns GetAllUsers
``` 
This PR introduces a simple and clean approach: always take a router that eats more route tokens (sort of greedy router). I also made a routing more strict - we don't route the requests whose path wasn't fully matched.
=> Greedy routers

json/src/main/scala/io/finch/json/Json.scala
`Json.encode` will be faster with `StringBuilder`. The implementation looks imperative (ugly?) but fast as hell. This addresses bullet N2 in #115.
=> Use SB in Json.ecnode

CONTRIBUTING.md, argonaut/src/test/scala/io/finch/argonaut/ArgonautSpec.scala, core/src/test/scala/io/finch/request/ApplicativeRequestReaderSpec.scala, core/src/test/scala/io/finch/request/BodySpec.scala, core/src/test/scala/io/finch/request/CookieSpec.scala, core/src/test/scala/io/finch/request/DecodeSpec.scala, core/src/test/scala/io/finch/request/HeaderSpec.scala, core/src/test/scala/io/finch/request/OptionalParamSpec.scala, core/src/test/scala/io/finch/request/OptionalParamsSpec.scala, core/src/test/scala/io/finch/request/RequestReaderCompanionSpec.scala, core/src/test/scala/io/finch/request/RequestReaderValidationSpec.scala, core/src/test/scala/io/finch/request/RequiredParamSpec.scala, core/src/test/scala/io/finch/request/RequiredParamsSpec.scala, core/src/test/scala/io/finch/response/ResponseBuilderSpec.scala, core/src/test/scala/io/finch/route/RouterSpec.scala, json/src/test/scala/io/finch/json/JsonSpec.scala
Work for #153. Note this changes the contributing.md as discussed in the issue.
=> unified the styles of all tests according to the new contributing.md

demo/src/main/scala/io/finch/demo/Main.scala, demo/src/main/scala/io/finch/demo/endpoint.scala, demo/src/main/scala/io/finch/demo/model.scala, demo/src/main/scala/io/finch/demo/package.scala, demo/src/main/scala/io/finch/demo/reader.scala, demo/src/main/scala/io/finch/demo/service.scala
Still work in progress. Hopefully, will merge it this weekend.
Planning to update docs also.
=> Fix #150: Update demo

docs.md
This is an almost complete rewrite of the section about request processing as outlined in this ticket: https://github.com/finagle/finch/issues/178.
This is probably difficult to review based on the diff, you can alternatively read the rendered version.
=> Restructure documentation for request package - fixes #178

core/src/main/scala/io/finch/package.scala, core/src/main/scala/io/finch/route/Router.scala
Realized that I used a wrong name for the `/` combinator.
=> Improve Router API

core/src/main/scala/io/finch/response/ResponseBuilder.scala, core/src/main/scala/io/finch/response/package.scala
=> Simplify RB.apply(String)

core/src/main/scala/io/finch/package.scala, core/src/main/scala/io/finch/route/package.scala, core/src/test/scala/io/finch/route/RouterSpec.scala, docs/index.md, docs/route.md
- Improve docs for `Router`
- Add `**` router that matches the whole route
=> Add ** router

argonaut/src/main/scala/io/finch/argonaut/package.scala, argonaut/src/test/scala/io/finch/argonaut/ArgonautSpec.scala, core/src/main/scala/io/finch/package.scala, core/src/main/scala/io/finch/request/RequestReader.scala, core/src/main/scala/io/finch/response/ResponseBuilder.scala, core/src/main/scala/io/finch/route/package.scala, core/src/test/scala/io/finch/route/RouterSpec.scala, jawn/src/main/scala/io/finch/jawn/pacakge.scala, jawn/src/test/scala/io/finch/jawn/JawnSpec.scala
=> Fix WartRemoval warnings + tiny code fixes

README.md, build.sbt, playground/README.md, playground/src/main/scala/io/finch/playgorund/Main.scala
=> Add playground

core/src/main/scala/io/finch/request/package.scala, core/src/test/scala/io/finch/request/OptionalParamSpec.scala, docs/request.md
Simple implementation based on scala `Option` methods
=> Ench #186: Default value for optional readers

README.md
Hello, we use finch in production, in several backend microservices - we love it.  We just launched a couple weeks ago.  Feel free to add us to your adopters list.  Thanks!!
=> Add Spright to adopters list

argonaut/src/main/scala/io/finch/argonaut/package.scala, build.sbt, core/src/main/scala/io/finch/micro/package.scala, core/src/main/scala/io/finch/request/package.scala, core/src/main/scala/io/finch/route/package.scala, demo/src/main/scala/io/finch/demo/service.scala, jawn/src/main/scala/io/finch/jawn/pacakge.scala, json/src/main/scala/io/finch/json/Json.scala, json/src/main/scala/io/finch/json/package.scala
=> Partially fixes 200

docs/route.md
The doc is now updated with the more simple route building feature that is available since 0.6.0
=> updating outdated doc

README.md, build.sbt, demo/src/main/scala/io/finch/demo/Main.scala, demo/src/main/scala/io/finch/demo/model.scala, demo/src/main/scala/io/finch/demo/reader.scala, docs/json.md, docs/response.md, json/README.md, json/src/main/scala/io/finch/json/Json.scala, json/src/main/scala/io/finch/json/package.scala
Added deprecation warnings and noted the deprecation in documentation. A start for #233. (should be noted that this adds a lot of warnings to our build).
Do we want to include updates to the demo package in this PR or do we want to do that when we remove the library entirely?
=> Deprecate Finch Json.

build.sbt, project/plugins.sbt
Now we just need to publish 0.7.0 so we can update the API docs so that we get linking to Finagle's.
=> Update versions, including Finagle (to 6.25.0)

build.sbt
This commit does two or three different things but they're minor enough that I thought I'd just submit them together.
First, the SBT console currently isn't very useful because every command results in "Unused import" warnings. This turns off those warnings in the console by defining the console's `scalacOptions` separately and omitting that warning.
To make the console more useful I've also made the root project depend on `core` and `argonaut` and have added a few initial imports. This means that a user who checks out the repository and types `sbt console` will immediately have a REPL where they can do interesting stuff. Adding these projects as dependencies for the root project doesn't have any other impact, since the root project is really only for aggregation. Since it's only for …
=> Clean up pom and make root project more useful

README.md, build.sbt, core/src/main/scala/io/finch/micro/package.scala
I went ahead and deprecated the micro style in favour of #221.
=> Deprecate micro-style

core/src/main/scala/io/finch/response/ResponseBuilder.scala, core/src/main/scala/io/finch/response/package.scala, core/src/test/scala/io/finch/request/ApplicativeRequestReaderSpec.scala, core/src/test/scala/io/finch/response/EncodeSpec.scala, core/src/test/scala/io/finch/response/ResponseBuilderSpec.scala, docs/endpoint.md
Fixes both issues #244 and #245.
Re #244: I hardcoded the content type to "application/octet-stream". Not sure if it's a right way to do that.
=> Fix #244 & Fix #245

README.md
Thanks for an awesome project :)
=> add Qubit to users

core/src/main/scala/io/finch/route/RouterN.scala, core/src/main/scala/io/finch/route/RouterNConversions.scala, demo/src/main/scala/io/finch/demo/endpoint.scala
Some fairly minor suggestions related to #278.
=> Some minor clean-up for router-service conversions

README.md
Also a good test to see if codecov.io PR commenting is on. We need to opt-in to that feature, so if we don't get a comment, it might not be on.
=> Fixed the broken codecov shield

README.md, docs/index.md, docs/json.md, jawn/src/main/scala/io/finch/jawn/package.scala
=> Deprecate finch-jawn (and update docs index)

auth/src/main/io/finch/auth/BasicallyAuthorize.scala, core/src/test/scala/io/finch/request/BodySpec.scala, json/src/test/scala/io/finch/json/JsonSpec.scala
Might as well avoid some Netty imports where it's easy.
=> Pick some low-hanging Netty fruit

core/src/test/scala/io/finch/request/BodySpec.scala, json/src/test/scala/io/finch/json/JsonSpec.scala
I should have caught these warnings in #296.
=> Fix implicit widening warnings

core/src/main/scala/io/finch/route/RouterN.scala
This is super trivial, but I noticed that there's some unnecessary noise in these pattern matches, and that the indentation could be a little clearer.
=> Minor clean-up for clarity

benchmarks/src/main/scala/io/finch/benchmarks/service/UserServiceBenchmark.scala, core/src/main/scala/io/finch/request/package.scala, core/src/test/scala/io/finch/request/MultipartParamSpec.scala, core/src/test/scala/io/finch/request/RequestReaderValidationSpec.scala, core/src/test/scala/io/finch/request/RequiredParamSpec.scala
=> A bit more coverage and some minor rearrangements and naming fixes

demo/src/test/scala/io/finch/demo/DemoSpec.scala
Stumbled upon this while reading through the code.
Partially addresses #298
=> remove netty reference in DemoSpec

demo/src/main/scala/io/finch/demo/Main.scala, demo/src/main/scala/io/finch/demo/model.scala, demo/src/main/scala/io/finch/demo/reader.scala
This makes it a little easier to get started with the demo project.
=> Add some example usage notes and initial data to the demo

docs/route.md
Fixed a broken link in routes.md.
=> Fix a broken link in doc

docs/request.md
Thanks to Michelle for bringing this to my attention.
=> Fix example in request docs

demo/src/main/scala/io/finch/demo/package.scala, demo/src/main/scala/io/finch/demo/service.scala
=> Removed implicit conversion in AuthRequest

.travis.yml, build.sbt
There are also new sbt-jmh versions but that's not a trivial upgrade so I didn't include it here.
=> Update Scala to 2.11.7, Finagle to 6.26.0, etc.

demo/src/test/scala/io/finch/demo/DemoSpec.scala, docs/quickstart.md
Minor follow-up to #342 to fix stuff noticed there but unrelated to it.
=> Fix a couple of old typos

CONTRIBUTING.md
I updated CONTRIBUTING.md with details about using Waffle.io while contributing to Finch.
=> Finch uses Waffle

build.sbt
Very minor change but I thought we might as well go ahead and get these in.
=> Update Shapeless and Finagle versions

core/src/main/scala/io/finch/route/Extractor.scala, core/src/test/scala/io/finch/route/RouterSpec.scala
See context [here](https://gitter.im/finagle/finch?at=55a7f5fc10602d6e64f797da).
@vkostyukov, @travisbrown please review.
Resolves #349
=> Add '*' method to Extractor to extract the tail of the path

petstore/src/main/scala/io/finch/petstore/endpoint.scala, petstore/src/main/scala/io/finch/petstore/petstoreDb.scala, petstore/src/test/scala/io/finch/petstore/PetstoreDbSpec.scala
To keep server-side and client-side separate. :)
=> Changed updatePetViaForm to updatePetNameStatus

core/src/main/scala/io/finch/route/Extractor.scala, core/src/test/scala/io/finch/route/RouterSpec.scala
This is a follow up PR for #353.
=> Refactor tail extractors

README.md, core/src/main/scala/io/finch/package.scala, core/src/main/scala/io/finch/route/package.scala, docs/auth.md, docs/demo.md, docs/endpoint.md, docs/index.md, docs/quickstart.md, docs/request.md, docs/route.md, petstore/README.md
The work is in progress.
I opened a PR to check how it's rendered.
=> Update docs as for 0.8

README.md
This PR adds a comparison table into a README. This doesn't look bad at all!
=> Add performance results

core/src/main/scala/io/finch/request/package.scala, core/src/test/scala/io/finch/request/MultipartParamSpec.scala, petstore/src/main/scala/io/finch/petstore/endpoint.scala, petstore/src/main/scala/io/finch/petstore/petstoreDb.scala
Resolves #402. Let me know what you think.
=> Use Finagle Multipart API instead of Netty Multipart API

build.sbt, core/src/main/scala/io/finch/Endpoint.scala, core/src/test/scala/io/finch/EndpointSpec.scala
This bug has been reported on [Gitter](https://gitter.im/finagle/finch?at=5631596490cea42a05840499) by @arnarthor.
=> Fix missing output when / or ap is used in composition

core/src/main/scala/io/finch/Endpoints.scala, core/src/test/scala/io/finch/EndpointSpec.scala
This PR improve the `basicAuth` combinator that is provided in `finch-core`:
1. Introduce a case class `BasicAuth` so users can create it once and reuse (and do not case about the  `Nothing` type infered).
2. Respond `Unautрorized` instead of `NotFound`.
=> Imporve Basic Auth

core/src/main/scala/io/finch/Output.scala, core/src/main/scala/io/finch/Outputs.scala, core/src/main/scala/io/finch/ToService.scala, core/src/test/scala/io/finch/ExtractorSpec.scala, core/src/test/scala/io/finch/FinchSpec.scala, petstore/src/main/scala/io/finch/petstore/ErrorHandling.scala
This PR contains the initial sketch of the propery-based testing for endpoints as well as some cleanups in error handling.
=> Clean up error handling & PB testing

core/src/main/scala/io/finch/Output.scala
https://gitter.im/finagle/finch?at=564301ec94df6212290da0db
in other case it makes no sense?
=> Fix for typo in Failure

benchmarks/src/main/scala/io/finch/benchmarks/service/FinchUserService.scala, core/src/main/scala/io/finch/Output.scala, core/src/main/scala/io/finch/Outputs.scala, core/src/main/scala/io/finch/ToService.scala, core/src/main/scala/io/finch/response/EncodeResponse.scala, core/src/test/scala/io/finch/BasicAuthSpec.scala, core/src/test/scala/io/finch/FinchSpec.scala, core/src/test/scala/io/finch/OutputSpec.scala, docs/request.md
We definetelly need to test them better: some initial step.
=> Add tests for Output

README.md, build.sbt, core/src/main/scala/io/finch/Endpoint.scala, core/src/main/scala/io/finch/Endpoints.scala, core/src/main/scala/io/finch/Mapper.scala, core/src/main/scala/io/finch/response/EncodeResponse.scala, core/src/main/scala/io/finch/response/Redirect.scala, core/src/main/scala/io/finch/response/ResponseBuilder.scala, core/src/main/scala/io/finch/response/package.scala, core/src/main/scala/io/finch/route/package.scala, core/src/test/scala/io/finch/response/RedirectSpec.scala, core/src/test/scala/io/finch/response/ResponseBuilderSpec.scala
I'm going to release 0.9.1 (source compatible tih 0.9.0) tonight.
=> Revert "Remove deprecated things as for 0.9.0"

core/src/main/scala/io/finch/Output.scala, core/src/main/scala/io/finch/ToService.scala, core/src/test/scala/io/finch/FinchSpec.scala, core/src/test/scala/io/finch/OutputSpec.scala
Refactor tests just a little bit.
=> Improve testing for Outputs

docs/best-practices.md, docs/index.md, docs/json.md
I've started working on Finch's Best Practices. Going to keep adding things there. Right now it's only about JSON libraries so feel free to open PRs with your personal thoughts and advices.
=> Add best-practices.md

argonaut/src/main/scala/io/finch/argonaut/package.scala, build.sbt
I just realized that the fix for jawn was pushed a long time ago and that the fix for #287 has just been sitting here. I'm not sure if we still want to make this change, but I'll leave it here for experimentation.
=> Use Jawn Parser for Argonaut

core/src/main/scala/io/finch/Outputs.scala
=> Use outputs from group #1

.travis.yml, build.sbt
It turned out there is Scala 2.10.6 already.
=> Bump Scala 2.10 version

build.sbt, project/build.properties
Somehow, `sbt console` was broken for me. Now it's fixed.
=> Update sbt and fix sbt console

README.md, build.sbt, core/src/main/scala/io/finch/EncodeResponse.scala, core/src/main/scala/io/finch/RequestReaders.scala, core/src/main/scala/io/finch/internal/ToService.scala, examples/src/main/scala/io/finch/div/Main.scala, examples/src/main/scala/io/finch/todo/Main.scala, examples/src/main/scala/io/finch/todo/Todo.scala, examples/src/main/scala/io/finch/todo/package.scala
=> Move some finch-101 examples under the Finch repo

core/src/main/scala/io/finch/RequestReaders.scala, core/src/main/scala/io/finch/package.scala, core/src/test/scala/io/finch/RequestReaderCompanionSpec.scala
Remove both `.toFuture` and `.toFutureException`.
=> Remove toFuture and toFutureException

build.sbt, core/src/test/scala/io/finch/FinchSpec.scala, core/src/test/scala/io/finch/OutputSpec.scala, core/src/test/scala/io/finch/internal/TooFastStringSpec.scala
Some pretty strighforward misses.
=> Increase code cov

build.sbt
Prepare release:
* Finagle 6.31
* Circe 0.2.1
* Cats 0.3.0
* Shapeless 2.2.5
=> Release 0.9.2

core/src/main/scala/io/finch/RequestReaders.scala, core/src/test/scala/io/finch/BodySpec.scala, core/src/test/scala/io/finch/FinchSpec.scala
This PR fixes a bug discovered in #483. Also new property-based tests would catch that bug if we make a regression.
=> Fix 483: string readers

build.sbt, circe/src/main/scala/io/finch/circe/Encoders.scala, circe/src/main/scala/io/finch/circe/package.scala
This PR is a copy of #491 (+ Jackson version updated).
=> Jackson Serializer for finch-circe

README.md
Our community grows and I think we need to explicitly support a code of conduct (i.e., Typelevel code of conduct). /cc @travisbrown
=> Typelevel code of conduct

docs/best-practices.md, docs/index.md
Added some missing imports to the best practices (#BlueSkyScala). Also tried to write up a first version of "Big Picture" that explains what an idiomatic Finch program look like.
=> Add the big picture

README.md
We've started to using finch while migrating from monolithic finatra app to microservices a few month ago.
=> Glopart in adopters list

README.md, build.sbt
=> Release 0.9.3

core/src/main/scala/io/finch/EncodeResponse.scala, docs/cookbook.md, docs/index.md, docs/json.md
Add an initial version of Cookbook. A great example of the recipe that should be included there is #347.
=> Add Cookbook

core/src/main/scala/io/finch/Endpoints.scala, examples/src/main/scala/io/finch/streaming/Main.scala
There are three new methods added in this PR: `streamingPost`, `streamingPut` and `streamingPatch` that only matches POST, PUT and PATCH chunked requests.
=> Introduce streamingMethod combonator

build.sbt, examples/src/main/scala/io/finch/streaming/Main.scala
Cats [0.4.0](https://github.com/typelevel/cats/releases/tag/v0.4.0) is here!
=> Update Cats to 0.4

docs/best-practices.md, docs/cookbook.md
Add parts about streaming and Finagle configuration.
=> Udpate cookbook and best-practices

build.sbt, core/src/main/scala/io/finch/RequestReaders.scala
Finagle 6.33 and Scalacheck 1.13 are here.
=> Update finagle and scalacheck

build.sbt
=> Update to circe 0.3.0 release

core/src/main/scala/io/finch/Endpoint.scala, core/src/main/scala/io/finch/Endpoints.scala, core/src/main/scala/io/finch/internal/Extractor.scala, docs/cookbook.md
Experimenting with the API for building custom patch matching endpoints (also added a new cookbook recipe).
=> Update cookbook with custom endpoints

docs/cookbook.md
=> Fix typo in cookbook

README.md, build.sbt, playjson/src/main/io/finch/playjson/package.scala, playjson/src/main/scala/io/finch/playjson/package.scala, playjson/src/test/scala/io/finch/playjson/PlayJsonSpec.scala
=> Play JSON support

docs/json.md
I never included this update in my initial PR because I wasn't sure I had all the instructions at the time because of compilation issues.
=> Updating JSON docs for Play Json

build.sbt, examples/src/main/scala/io/finch/oauth2/InMemoryDataHandler.scala, examples/src/main/scala/io/finch/oauth2/Main.scala, examples/src/main/scala/io/finch/oauth2/OAuthUser.scala
@vkostyukov please take a look.
=> Add example for finch-oauth2. Resolves #540.

core/src/main/scala/io/finch/Endpoint.scala, core/src/test/scala/io/finch/AlternativeEndpointSpec.scala, core/src/test/scala/io/finch/FinchSpec.scala, core/src/test/scala/io/finch/MissingInstances.scala
=> Implementation of cat's Applicative for Endpoint

core/src/main/scala/io/finch/Endpoint.scala, core/src/test/scala/io/finch/EndpointSpec.scala
=> Endpoint.transform and Output.transform methods

core/src/main/scala/io/finch/Encode.scala, core/src/test/scala/io/finch/EncodeLaws.scala, core/src/test/scala/io/finch/EncodeSpec.scala, core/src/test/scala/io/finch/MissingInstances.scala, examples/src/main/scala/io/finch/div/Main.scala
=> Allow encoding A with Show as plain text

docs/cookbook.md
=> fixed a typo in cookbook.md

core/src/main/scala/io/finch/Encode.scala
Simple encoder for #504
Still there is a question about dynamic `contentType`.
=> Cat's Xor Encoder

build.sbt, examples/src/main/scala/io/finch/todo/package.scala
Let's just pretend 0.4.0 didn't happen. :smile:
=> Update circe to 0.4.1 and avoid deprecated methods in exmaple

docs/best-practices.md, docs/cookbook.md
1. CORS
2. Filter vs. Endpoint
=> Update BR/CB with new items

docs/cookbook.md
The existing authentication example is helpful, but it's very common for auth to require external calls, so it seems worth including an example in the Cookbook.
=> Add async authentication example to Cookbook

docs/auth.md, docs/best-practices.md, docs/cookbook.md, docs/endpoint.md, docs/json.md
I'm currently experimenting with Finch (having a great time btw, so thanks for that).
So, naturally, I went through the doc (which are also great :smile: ) and found a few typos.
This PR aims to fix those I found.
=> Fix the different typos in the doc

core/src/main/scala/io/finch/Endpoint.scala, core/src/main/scala/io/finch/Endpoints.scala, core/src/main/scala/io/finch/internal/FromParams.scala
=> Add root and Endpoint.empty endpoints

README.md, build.sbt, docs/index.md
=> Prepare 0.11-M1 release

build.sbt, core/src/main/scala/io/finch/Output.scala, core/src/main/scala/io/finch/internal/ToResponse.scala
I realised that I missed porting the `ToResponse[Response]` instance.
=> ToResponse for Response

core/src/main/scala/io/finch/Encode.scala, core/src/main/scala/io/finch/internal/ToResponse.scala, core/src/test/scala/io/finch/EncodeLaws.scala, core/src/test/scala/io/finch/EncodeSpec.scala, core/src/test/scala/io/finch/EndpointSpec.scala, core/src/test/scala/io/finch/FinchSpec.scala, examples/src/main/scala/io/finch/streaming/Main.scala
This was preventing `toService` from compiling successfully.
=> Fix priority of AnsyncStream encoders

README.md, docs/index.md
=> Prepare M2 release

README.md
Sigma's entire API server is built with Finch
=> Add Sigma to Finch "Adopters" list in README.md

core/src/main/scala/io/finch/internal/ToResponse.scala, docs/cookbook.md, docs/endpoint.md, docs/json.md
This PR updates docs as per 0.11-M2 (see #614).
=> Updates docs to 0.11-M2

core/src/main/scala/io/finch/Input.scala, core/src/main/scala/io/finch/Output.scala, core/src/test/scala/io/finch/FinchSpec.scala, core/src/test/scala/io/finch/InputSpec.scala
=> Endpoint testing

README.md, benchmarks/src/main/scala/io/finch/benchmarks/EndpointBenchmark.scala, build.sbt, core/src/main/scala/io/finch/Output.scala, core/src/test/scala/io/finch/EndpointSpec.scala, docs/best-practices.md, docs/endpoint.md, docs/index.md, examples/src/main/scala/io/finch/oauth2/Main.scala
This PR prepares a release: updates the docs and makes some tiny cleanups.
=> Prepare 0.11-M3

docs/best-practices.md, docs/endpoint.md
Add link to a new Finagle blog post and clean up a couple of places.
=> Add block party blog post

docs/cookbook.md
based on feedback from @chbrown in #644 . Let me know if there are issues.
=> Update Static File doc

core/src/main/scala/io/finch/Input.scala, core/src/test/scala/io/finch/InputSpec.scala, docs/endpoint.md, examples/src/test/scala/io/finch/todo/TodoSpec.scala
=> Make Input accept json

build.sbt, project/plugins.sbt
Since scoverage/sbt-scoverage#146 is fixed we might as well update scoverage.
=> Upgrade scoverage

core/src/main/scala/io/finch/internal/ToResponse.scala, core/src/test/scala/io/finch/internal/ToResponseSpec.scala
=> Fix priority of 'ToResponse' instances for 'AsyncStream[Buf]'

core/src/main/scala/io/finch/internal/ToResponse.scala, docs/cookbook.md
com.twitter.finagle.Response doesn't exists.
=> Invalid class path reference in Documentation

README.md, docs/cookbook.md
Updates README with new project and slightly restructures the cookbook example.
=> Update README with new SSE package

docs/cookbook.md
Adopted from my [SO answer](http://stackoverflow.com/questions/40497730/finch-endpoint-to-support-jsonp/40498499#40498499).
=> Add JSONP recepie to the Cookbook

core/src/main/scala/io/finch/Endpoint.scala, core/src/test/scala/io/finch/EndpointSpec.scala
=> body.as[CaseClass] should fail with Error.NotParsed

core/src/main/scala/io/finch/Encode.scala, core/src/test/scala/io/finch/OutputSpec.scala, sse/src/main/scala/io/finch/sse/ServerSentEvent.scala
=> Polymorphic Encode[Exception]

build.sbt, core/src/main/scala/io/finch/Endpoint.scala, core/src/main/scala/io/finch/Endpoints.scala, core/src/main/scala/io/finch/Error.scala, core/src/main/scala/io/finch/package.scala, core/src/test/scala/io/finch/EndpointSpec.scala
We did a release so let's remove deprecations.
=> Remove deprecated methods

README.md, docs/auth.md, docs/best-practices.md, docs/cookbook.md, docs/index.md, docs/json.md, docs/user-guide.md
Reflect the changes in the docs. Still WIP.
=> Update docs to 0.11

core/src/main/scala/io/finch/Endpoint.scala, core/src/main/scala/io/finch/Output.scala, core/src/main/scala/io/finch/internal/ToService.scala, core/src/main/scala/io/finch/internal/package.scala, core/src/test/scala/io/finch/EndpointSpec.scala, core/src/test/scala/io/finch/OutputSpec.scala, core/src/test/scala/io/finch/internal/ToResponseSpec.scala, core/src/test/scala/io/finch/internal/ToServiceSpec.scala
There is an issue #700 that would have been discovered if we had a test.
=> Impove tests for ToService

README.md
Add D.A.Consortium as an adopter. We are using finch in production environment for over a year :)
=> Add D.A.Consortium as an adopter

core/src/main/scala/io/finch/Endpoint.scala
To optimize the number of allocations and save ecology with creating less instances. It means consuming less power when computing the result. 
Taking in mind how many adopters finch would have in a very near future this PR is clearly aimed to save the whole planet.
=> [#692] Add productWith and replace `product` calls with a new one

README.md
Added Redbubble to list of adopters in README.
=> Added Redbubble to README

.travis.yml, argonaut/src/main/scala/io/finch/argonaut/Decoders.scala, build.sbt
=> Scala 2.12.0 + dependencies versions update

benchmarks/src/main/scala/io/finch/benchmarks.scala
Need some accurate numbers for the upcoming talk.
=> Add JsonBenchmark (Circe)

core/src/main/scala/io/finch/internal/ToService.scala, core/src/main/scala/io/finch/internal/currentTime.scala, core/src/test/scala/io/finch/internal/ToServiceSpec.scala
=> Include Date header in any Finch response

docs/cookbook.md
=> Fixed SSE example in cookbook

core/src/test/scala/io/finch/OutputSpec.scala
This merge request aims to increase the coverage of the `Output` class.
=> Add tests to increase Output coverage.

core/src/main/scala/io/finch/internal/package.scala
We want to allow users to try out Netty 4 in the next release. We better make sure there are no "unexpected" regressions in the throughput.
=> Make retrieving the underlying byte array Netty-agnostic (for real)

core/src/main/scala/io/finch/internal/package.scala, core/src/test/scala/io/finch/FinchSpec.scala, core/src/test/scala/io/finch/internal/HttpContentSpec.scala, jackson/src/main/scala/io/finch/jackson/package.scala
This is supposed to fix #747. I will backport this PR into 0.13 and release it as 0.13.1.
=> Fix HttpContent converters (Netty 4)

build.sbt, project/plugins.sbt
I'm not entirely sure about `sbt-ghpages` changes😢.
Migration Guide is [here](http://www.scala-sbt.org/sbt-site/migration-guide.html#adding-custom-mappings-to-a-site-directory).
=> Update sbt plugins

README.md
Hi.
I added My Company to the Adopters.
=> add Rakuten to Adopters.

build.sbt, docs/src/main/tut/cookbook.md, docs/src/main/tut/index.md, docs/src/main/tut/user-guide.md
Updated the base url to just point to root and used some Scala REPL output whenever it made sense.
=> Tiny changes to microsite

build.sbt
See https://github.com/typelevel/scala/issues/135.
=> Use scalaOrganization.value.

docs/src/main/tut/user-guide.md
I'm not entirely sure about some of the fixes (like compositor). Please review carefully.
=> Fix document

NOTICE, README.md, build.sbt
Shamelessly copied from Circe's README file.
=> Add note about maintainers

docs/src/main/tut/best-practices.md
Added new Redbubble & other service templates.
=> New service templates

circe/src/main/scala/io/finch/circe/Encoders.scala, circe/src/main/scala/io/finch/circe/package.scala
Fixes #768. Will be published as 0.14.1.
=> Revert Binary Printing for Circe

core/src/main/scala/io/finch/Endpoints.scala, core/src/main/scala/io/finch/endpoint/fileUpload.scala, core/src/main/scala/io/finch/endpoint/path.scala, core/src/main/scala/io/finch/internal/Rs.scala
Extracting file uploads into their own file/scope.
=> Add FileUploads

argonaut/src/main/scala/io/finch/argonaut/Encoders.scala, argonaut/src/test/scala/io/finch/argonaut/ArgonautSpec.scala, circe/src/main/scala/io/finch/circe/Encoders.scala, jackson/src/main/scala/io/finch/jackson/package.scala, json-test/src/main/scala/io/finch/test/AbstractJsonSpec.scala, json4s/src/main/scala/io/finch/json4s/package.scala, playjson/src/main/scala/io/finch/playjson/package.scala, sprayjson/src/main/scala/io/finch/sprayjson/package.scala
Removed the instances for encoding Exceptions as json as per https://github.com/finagle/finch/issues/765.
=> Remove encoding for exceptions from all of the json projects.

build.sbt
- Circe 0.8
- Circe-Jackson 0.8
- Finagle 6.44 (Util 6.43, TS 1.29, etc)
Pending finagle-oauth2 release (since we're here I think we should move that out of this repo so it's easier to bump dependencies).
=> Update some dependencies

argonaut/src/main/scala/io/finch/argonaut/Encoders.scala, core/src/main/scala/io/finch/Endpoints.scala, core/src/main/scala/io/finch/endpoint/body.scala, core/src/main/scala/io/finch/endpoint/fileUpload.scala, core/src/main/scala/io/finch/endpoint/header.scala, core/src/main/scala/io/finch/internal/Rs.scala, scalastyle-config.xml
Moving `header` endpoints into their own file.
=> Introduce Header

core/src/main/scala/io/finch/Endpoints.scala, core/src/main/scala/io/finch/endpoint/param.scala, core/src/main/scala/io/finch/internal/Rs.scala
Following the structure of the rest of the endpoints.
It's pretty verbose so far (and I'm not happy about that), but I'll make sure to revisit and see if there is anything we could share between the new classes.
=> Introduce Param and Params

core/src/main/scala/io/finch/Endpoint.scala, core/src/main/scala/io/finch/Endpoints.scala, core/src/main/scala/io/finch/endpoint/cookie.scala, core/src/main/scala/io/finch/internal/Rs.scala
Introducing cookies and removing `Endpoint.embed` (yay!).
=> Introduce Cookie

.travis.yml, build.sbt, project/build.properties, project/plugins.sbt
I just published a new catbird for Util 6.45.0, but it looks like Finch was behind a release anyway.
=> Update catbird and other versions

build.sbt, core/src/main/scala/io/finch/Endpoint.scala, core/src/main/scala/io/finch/Endpoints.scala, core/src/test/scala/io/finch/EncodeLaws.scala, core/src/test/scala/io/finch/EndpointSpec.scala, sse/src/test/scala/io/finch/sse/ServerSentEventSpec.scala
=> Remove deprecated methods as of 0.15

core/src/main/scala/io/finch/internal/currentTime.scala
I guessed less volatile-write/volatile-read and fewer allocations should make better throughput. Our benchmarks confirm that:
```
NEW:
[info] Benchmark                 Mode  Cnt      Score      Error  Units
[info] ToServiceBenchmark.foos  thrpt   10  16926.371 ± 1064.238  ops/s
[info] ToServiceBenchmark.ints  thrpt   10  83259.967 ± 1871.973  ops/s
OLD:
[info] Benchmark                 Mode  Cnt      Score      Error  Units
[info] ToServiceBenchmark.foos  thrpt   10  15527.904 ±  678.066  ops/s
[info] ToServiceBenchmark.ints  thrpt   10  79637.599 ± 3721.304  ops/s
```
Our end-to-end score increased by 1k reqs/s (or 3%): 31823.32 vs. 32772.02
=> Use ThreadLocal in currentTime

core/src/main/scala/io/finch/Bootstrap.scala, core/src/main/scala/io/finch/Output.scala, core/src/main/scala/io/finch/ToResponse.scala, core/src/main/scala/io/finch/ToService.scala, sse/src/main/scala/io/finch/sse/ServerSentEvent.scala
=> Move ToResponse/ToService under io.finch

core/src/main/scala/io/finch/Bootstrap.scala, core/src/main/scala/io/finch/ToService.scala
=> Add bootstrap options

core/src/main/scala/io/finch/Endpoint.scala
Current implementation ends up with infinite recursion. Fix argument name
=> Fix withToString recursion

docs/src/main/tut/user-guide.md
I've updated the documentation for Encoding Json Exceptions as part of #806. Let me know if there are any changes that would make these docs more clear.
=> Update documentation about defining Exception Encoders for Json.

build.sbt
=> Bump finagle/ts/catbird

build.sbt, docs/src/main/tut/cookbook.md, docs/src/main/tut/user-guide.md
=> Fix compile errors in docs

docs/src/main/tut/user-guide.md
Related to https://github.com/finagle/finch/issues/822
=> Add docs for finch-iteratee module

README.md, docs/src/main/tut/index.md, docs/src/main/tut/user-guide.md
=> More docs fixes

build.sbt
Also 
- TS to 1.32 and
- Catbird to 0.18
Fixes #841
=> Update Finagle to 7.1

core/src/main/scala/io/finch/endpoint/path.scala
=> Deprecate old-style path matchers

core/src/main/scala/io/finch/syntax/Mapper.scala
@vkostyukov 
Seems that this fix will finally solves https://github.com/finagle/finch/issues/631
=> Fix Intellij IDEA syntax error

build.sbt, examples/src/main/scala/io/finch/todo/Main.scala
New version was released few days ago
Also update catbird & iteratee
=> Update finagle to 17.10.0

README.md, build.sbt, core/src/main/scala/io/finch/Endpoint.scala, core/src/test/scala/io/finch/EncodeLaws.scala, core/src/test/scala/io/finch/syntax/MapperSyntaxSpec.scala, docs/src/main/tut/index.md
Bumps version;
Cleans up some warnings;
=> Release 0.16-M4

.travis.yml, build.sbt
No rush on this but all the dependencies are now available.
=> Update versions for 17.11.0

docs/src/main/tut/best-practices.md, docs/src/main/tut/cookbook.md, docs/src/main/tut/user-guide.md
Mostly cleanups around `path` vs. `string`, etc.
=> Docs cleanup

project/build.properties
Fixes performance regression
See https://github.com/sbt/sbt/releases/tag/v1.0.4
=> Bump sbt to 1.0.4

README.md, build.sbt, docs/src/main/tut/index.md
=> Upgrade to Cats RC-2

README.md, build.sbt
Adding @ImLiar as a Finch maintainer.
=> Welcome Sergey!

README.md
Move from submodules to related projects
=> Update README info about finch-oauth2

build.sbt, docs/src/main/tut/best-practices.md, docs/src/main/tut/cookbook.md, docs/src/main/tut/index.md, docs/src/main/tut/user-guide.md, project/build.properties, project/plugins.sbt
I've published [catbird](https://github.com/travisbrown/catbird/releases/tag/v18.1.0) and [iteratee-twitter](https://github.com/travisbrown/iteratee-twitter) for 18.1.0, so this is ready whenever you are. I've also bumped some sbt versions and fixed the microsite build (it might be worth having CI check this?).
=> Update to 18.1.0

benchmarks/src/main/scala/io/finch/benchmarks.scala, core/src/main/scala/io/finch/Accept.scala, core/src/main/scala/io/finch/Bootstrap.scala, core/src/main/scala/io/finch/NegotiateToResponse.scala, core/src/main/scala/io/finch/Output.scala, core/src/main/scala/io/finch/ToResponse.scala, core/src/main/scala/io/finch/ToService.scala, core/src/test/scala/io/finch/FinchSpec.scala, core/src/test/scala/io/finch/NegotiateToResponseSpec.scala
=> Content Type Negotiation

build.sbt, core/src/main/scala/io/finch/endpoint/multipart.scala, project/plugins.sbt
I've just published new releases for [Catbird](https://github.com/travisbrown/catbird/releases/tag/v18.2.0) and [iteratee-twitter](https://github.com/travisbrown/iteratee-twitter/releases/tag/v0.20.0).
=> Update to 18.2.0

core/src/main/scala/io/finch/endpoint/multipart.scala
I considered several possible implementations for this but decided to settle on `Request.Schema` (mostly) for the sake of efficiency. Alternative solutions are
- Include `Option[Multipart]` into our `Input` and explicitly propagate it between endpoints (would increase allocations on each endpoint evaluation)
- Using Twitter Locals (really powerful but comes at the high cost of allocations)
Wonder if I'm missing any other possible solution?
=> Make sure Multipart isn't decoded multiple times

build.sbt, circe/src/main/scala/io/finch/circe/package.scala, circe/src/test/scala/io/finch/circe/test/CirceSpec.scala
=> Remove circe-jackson dependency

core/src/test/scala/io/finch/ExtractPathLaws.scala
Related to https://github.com/finagle/finch/pull/917
_P.S. I was busy with moving to the new flat, sorry for the delay_
=> Fix ExtractPathLaws spec

build.sbt, project/build.properties
I've published catbird and iteratee-twitter for 18.3.0, so these are ready whenever Finch is!
=> Update to 18.3.0

.travis.yml, build.sbt, project/build.properties, project/plugins.sbt
…I also went ahead and bumped Cats to 1.1.0.
=> Update Util, etc. to 18.4.0

.travis.yml, build.sbt, project/build.properties, project/plugins.sbt
I've published releases for catbird and iteratee-twitter.
=> Update to 18.5.0

build.sbt, project/build.properties, project/plugins.sbt
I've just published catbird and iteratee-twitter, so this should be ready to go. I've also bumped a few other little things while I was here.
=> Update to 18.6.0

core/src/main/scala/io/finch/endpoint/header.scala, core/src/main/scala/io/finch/endpoint/param.scala
As per #941 so we can remove them in 0.22.
=> Deprecate exist* endpoints

core/src/main/scala/io/finch/endpoint/header.scala, core/src/main/scala/io/finch/endpoint/param.scala
=> Remove deprecated APIs as of 0.21

core/src/main/scala/io/finch/ToService.scala, core/src/main/scala/io/finch/Trace.scala, core/src/test/scala/io/finch/BootstrapSpec.scala
As discussed in #959. Here is how it works (from the user perspective).
```scala
scala> import io.finch._, io.finch.syntax._
import io.finch._
import io.finch.syntax._
scala> val foo = get("foo" :: path[String]) { s: String => Ok(s) }
foo: io.finch.Endpoint[String] = GET /foo :: :string
scala> import com.twitter.finagle.http.Request
import com.twitter.finagle.http.Request
scala> val s = foo.toServiceAs[Text.Plain]
s: com.twitter.finagle.Service[com.twitter.finagle.http.Request,com.twitter.finagle.http.Response] = io.finch.ToService$$anon$4$$anon$2
scala> Trace.capture { s(Request("/foo/bar")).map(_ => Trace.captured) }
res0: com.twitter.util.Future[io.finch.Trace] = Promise@406161512(state=Done(Return(/foo/:string)))
```
=> Capture Traces

build.sbt, project/plugins.sbt
I just published catbird and iteratee-twitter. Release notes for the Twitter libraries are [here](https://finagle.github.io/blog/2018/07/11/release-notes/).
=> Update to Finagle 18.7.0

docs/src/main/tut/index.md, docs/src/main/tut/user-guide.md
=> Add docs for Trace

build.sbt
=> Update to 18.8.0 for Finagle, etc.

build.sbt
Thanks to @fwbrasil for release!
=> Bump Arrows to 0.1.22

build.sbt, iteratee/src/main/scala/io/finch/iteratee/package.scala, iteratee/src/test/scala/io/finch/iteratee/EnumerateEndpointSpec.scala
I've just published a new batch of releases for 18.9.0 and cats-effect 1.0.0.
=> Update Twitter deps and iteratee.io

.gitignore, build.sbt, core/src/main/scala/io/finch/endpoint/body.scala, core/src/test/scala/io/finch/ToResponseSpec.scala, docs/src/main/tut/index.md
We need a normal Finch release as well.
=> Prepare a normal Finch release 0.25

build.sbt, version.sbt
bump minor version for next auto release
fixes #1009
=> Fix for #1009 - bumps minor version on next auto release

version.sbt
=> Release 0.27.1

core/src/main/scala/io/finch/Endpoint.scala
=> Deprecate asyncBody

core/src/main/scala/io/finch/Compile.scala, core/src/main/scala/io/finch/Endpoint.scala, examples/src/main/scala/io/finch/middleware/Main.scala
So I wanted to make a usability check on the new mechanism. Would be nice to get a feedback if it's the right way to compose functions.
=> Example on using Endpoint.Compiled

core/src/main/scala/io/finch/internal/package.scala, core/src/test/scala/io/finch/internal/HttpMessageSpec.scala
The new test would fail with the current implementation.
See https://github.com/twitter/finagle/commit/e6e455c32db620c5ecbd1105ee3e29b57c373aff for more details.
=> Fix bug in charsetOrUtf8

build.sbt, core/src/main/scala/io/finch/Input.scala
=> Upgrade to Finagle 19.4.0 #1113

core/src/main/scala/io/finch/Endpoint.scala, core/src/test/scala/io/finch/EndpointSpec.scala
Add support for natural transformation of endpoint's effect
=> Add Endpoint.mapK

.github/workflows/build.yml
=> Use GitHub actions for builds

build/build.sh
finishes work left from #1461 
only decrypt release files on `push`
=> moves decrypt within push branch

build.sbt
=> Remove dependency on organize imports scalafix rule
