finagle/finch

README.md, build.sbt
Hey @rpless, @vkostyukov,
This is just a suggestion, but Finagle (and some associated Twitter projects) use `/docs/` for the API documentation, and I've made the change here for consistency. Thanks for setting up sbt-unidoc, @rpless!
=> Use docs directory for API docs on GitHub pages

README.md
Sorry I missed these the first time around. I've left the names the same, since the artifacts will have the prefix.
=> Fix subproject links

build.sbt, core/src/test/scala/io/finch/request/OptionalParamsSpec.scala
For #129. Doesn't include `Xlint` and "Xfatal-warnings" for reasons discussed in the issue.
=> Scalac flags

README.md, argonaut/src/test/scala/io/finch/argonaut/ArgonautSpec.scala, build.sbt, core/src/main/scala/io/finch/request/package.scala, core/src/main/scala/io/finch/response/package.scala, core/src/test/scala/io/finch/request/BodySpec.scala, jackson/README.md, jackson/src/main/scala/io/finch/jackson/package.scala, jackson/src/test/scala/io/finch/jackson/Foo.scala, jackson/src/test/scala/io/finch/jackson/JacksonSpec.scala
I implemented the basic Jackson support. Everything works almost fine except using Jackson via `RequestReader` (but I've found suitable [workaround](https://github.com/finagle/finch/pull/143/files#diff-5c501b7d1666db0ef25e62bb7109fc75R51)): `implicit val codec = decodeJackson[Foo]`. We don't need to do the opposite thing for encoding sine it works just fine. 
Any thoughts no how to avoid declaring the `decodeJackson` explicitly?
=> Add Jackson support #133

build.sbt
The artifact name problem was my fault—when I ported from `Build.scala` to `build.sbt` I forgot to remove the deprecated `Defaults.defaultSettings`. This meant that if `moduleName` was set before `baseSettings`, it got ignored. Removing the old-style default configuration fixes the build (artifact names include the prefix) and is more idiomatic than changing the project identifiers.
=> Fix build by removing deprecated default configuration

core/src/main/scala/io/finch/request/package.scala, core/src/test/scala/io/finch/request/ApplicativeRequestReaderSpec.scala
This adds applicative behaviour to the RequestReader. It is essential for comprehensive error handling as it collects all errors instead of the existing monadic behaviour which is fail-fast.
A monadic reader written with the current API:
``` scala
val intTuple: RequestReader[(Int, Int)] = for {
a <- RequiredIntParam("a")
b <- RequiredIntParam("b")
} yield (a, b)
```
can be rewritten in applicative style like this:
``` scala
val intTupleApplicative: RequestReader[(Int, Int)] = 
(RequiredIntParam("a") ~
RequiredIntParam("b")) { 
case a ~ b => (a, b)
}
```
None of the existing APIs are affected by this addition.
The functionality has been added without introducing new dependencies like scalaz. The generic applicative builder has been kept separate from the (very little) code which is …
=> add applicative behaviour to RequestReader. Fixes #145

core/src/main/scala/io/finch/route/package.scala, core/src/test/scala/io/finch/route/RouterSpec.scala
This is an initial implementation of route combinators as discussed in #146. There is no DSL layer yet - just raw classes. So, for now we have to explicitly create new instances like `StringMatcher` and `StringExtractor`. The next step would be to write a bunch of implicit conversion in order to enable full-featured DSL.
But now I wanted to collect a feedback and ask for an advice. I don't really think we need both `RouteMatcher` and `RouteExtractor`. My primary goal now is to replace them both with just `Router`. I would love to hear your advices @pasviegas, @benjumanji, @rodrigopr and @rpless on how can we achieve it.
The main problem here is that there are routers that don't extract anything but match something: `Get`, `StringMatcher`. So, the problem is in `RouteExtractor.flatMap` …
=> Intoroduce io.finch.route package

core/src/main/scala/io/finch/request/package.scala, core/src/test/scala/io/finch/request/BodySpec.scala, core/src/test/scala/io/finch/request/CookieSpec.scala, core/src/test/scala/io/finch/request/HeaderSpec.scala, core/src/test/scala/io/finch/request/OptionalParamSpec.scala, core/src/test/scala/io/finch/request/OptionalParamsSpec.scala, core/src/test/scala/io/finch/request/RequestReaderValidationSpec.scala, core/src/test/scala/io/finch/request/RequiredParamSpec.scala, core/src/test/scala/io/finch/request/RequiredParamsSpec.scala
This PR has a basic validation dsl for request readers as in #26. It takes the form of a `when` method on `RequestReader`s.
Basic usage looks like:
```scala
val user: RequestReader[User] = for {
name <- RequiredParam("name").when("should be greater then 5 symbols") { name.length > 5 }
} yield User(userId, name, Seq.empty[Ticket])
```
Would love to get some feedback on this.
=> Validation DSL

core/src/main/scala/io/finch/package.scala, core/src/main/scala/io/finch/route/package.scala
Revised the scaladoc for the `io.finch` package. Added `Endpoint` for routers.
=> Update scaladoc. Add endpoint for routers

.gitignore, argonaut/src/main/scala/io/finch/argonaut/package.scala, argonaut/src/test/scala/io/finch/argonaut/ArgonautSpec.scala, core/src/main/scala/io/finch/request/package.scala, core/src/test/scala/io/finch/request/BodySpec.scala, core/src/test/scala/io/finch/request/DecodeSpec.scala, docs.md, jackson/src/main/scala/io/finch/jackson/package.scala, jackson/src/test/scala/io/finch/jackson/JacksonSpec.scala, jawn/src/main/scala/io/finch/jawn/pacakge.scala, jawn/src/test/scala/io/finch/jawn/JawnSpec.scala, json/src/main/scala/io/finch/json/package.scala
This is the 2nd of 5 PRs extracted from https://github.com/finagle/finch/pull/162.
It is exactly as reviewed in the discussion PR except for:
* made all the changes requested in comments in https://github.com/finagle/finch/pull/162
This is the description for this PR, copied from the discussion PR:
This is also very unlikely controversial. The existing API was insufficient for proper error handling.
Returning an `Option` is usually not a good idea in APIs where details about the failure may be helpful.
The new API is simply:
```scala
trait DecodeAnyRequest {
def apply[A: ClassTag](req: String): Try[A]
}
```
This PR also makes all necessary adaptions for the various JSON integrations (Argonaut, Jawn, Jackson, Finch JSON).
Note that Finch JSON still does not report any error detail, as the …
=> improve DecodeRequest API to return Try instead of Option

core/src/main/scala/io/finch/request/package.scala, core/src/test/scala/io/finch/request/DecodeSpec.scala, core/src/test/scala/io/finch/request/OptionalParamsSpec.scala, core/src/test/scala/io/finch/request/RequiredParamsSpec.scala, docs.md
This is the 3rd of 5 PRs extracted from https://github.com/finagle/finch/pull/162.
It is exactly as reviewed in the discussion PR except for:
* fixed the compilation issue for Scala 2.10 which was actually caused by a compiler bug, through removing `extends AnyVal` from the implicit classes (as long as we support 2.10)
* fixed issues around `DecodeAnyRequest` and implicit resolution through making the magnet based on `DecodeAnyRequest` lower priority and added a test in `DecodeSpec` to prove this actually works
Note that two files show up as completely changed as someone checked them in with Windows line breaks. I'm not sure what the project's policy is regarding `autocrlf` settings.
This is the description for this PR, copied from the discussion PR:
This has not yet been discussed …
=> Add an implicit as[A] method to all string-based RequestReaders

core/src/main/scala/io/finch/request/optional.scala, core/src/main/scala/io/finch/request/package.scala, core/src/test/scala/io/finch/request/ApplicativeRequestReaderSpec.scala, core/src/test/scala/io/finch/request/BodySpec.scala, core/src/test/scala/io/finch/request/CookieSpec.scala, core/src/test/scala/io/finch/request/DecodeSpec.scala, core/src/test/scala/io/finch/request/HeaderSpec.scala, core/src/test/scala/io/finch/request/OptionalParamSpec.scala, core/src/test/scala/io/finch/request/OptionalParamsSpec.scala, core/src/test/scala/io/finch/request/RequiredParamSpec.scala, core/src/test/scala/io/finch/request/RequiredParamsSpec.scala, demo/src/main/scala/io/finch/demo/Main.scala, docs.md, json/src/main/scala/io/finch/json/package.scala
This is the 4th of 5 PRs extracted from #162.
It is exactly as reviewed in the discussion PR except for:
* Changed the name of the `mapFuture` method to `embedFlatMap` as discussed in the other PR
* Adjusted syntax of new test methods to be aligned with the new contribution guide
* Added more detail for the description for 2) below to make the motivation for this big refactoring clearer
* Added back `extends AnyVal` in two of the three implicit classes for `as[A]` as the simplification of the implementation did no longer trigger the compiler bug there
This is really two PRs in one, but since both require a bigger refactoring it would have been too cumbersome to split this work
The error handling has already been discussed here: https://github.com/finagle/finch/issues/26#issuecomment-723857 …
=> Unify error handling and simplify implementation of request package - fixes #157

README.md, core/src/main/scala/io/finch/route/package.scala, core/src/test/scala/io/finch/route/RouterSpec.scala
I need some help with it. What I want to achieve is to allow users mix routers of both futures and services into a endpoint. Like this:
```scala
val e: Endpoint[A, B] = (Get / "a" /> b.toFuture) | (Get / "b" /> bService)
```
For now, I only managed to solve it by [specifying the type explicitly](https://github.com/finagle/finch/commit/1bb7e3b82d4788131969c07bb1044f468ce1ea2e#diff-15fab5bf685af131056294bdbbcd0950R178). What we want to do is to probably chain implicit conversion, which seems to be possible according to this [SO question](http://stackoverflow.com/questions/5332801/how-can-i-chain-implicits-in-scala). I can't really figure out how to do it. It feels like we have to change the `orElse` method on router.
=> Improve implicit convertsion from router to service/endpoint

argonaut/src/main/scala/io/finch/argonaut/package.scala, argonaut/src/test/scala/io/finch/argonaut/ArgonautSpec.scala, core/src/main/scala/io/finch/request/optional.scala, core/src/main/scala/io/finch/request/package.scala, core/src/test/scala/io/finch/request/ApplicativeRequestReaderSpec.scala, core/src/test/scala/io/finch/request/BodySpec.scala, core/src/test/scala/io/finch/request/OptionalParamsSpec.scala, core/src/test/scala/io/finch/request/RequestReaderCompanionSpec.scala, core/src/test/scala/io/finch/request/RequestReaderValidationSpec.scala, core/src/test/scala/io/finch/request/RequiredParamsSpec.scala, demo/src/main/scala/io/finch/demo/Main.scala, docs.md, jackson/src/test/scala/io/finch/jackson/JacksonSpec.scala, json/src/test/scala/io/finch/json/JsonSpec.scala
This is the last of 5 PRs extracted from #162.
It is exactly as reviewed in the discussion PR except for:
* Renamed `RequestReaderErrors` and `RequestReaderError` to `RequestErrors` and `RequestError`
* Deprecated `Required/OptionalArrayBody` in favour of `Required/OptionalBinaryBody`
* Rewrote the description below to capture all the discussions that happened in the meantime
The recent series of PRs has made the request package more feature-rich and consistent. This would be a great opportunity to deprecate some of the older APIs which are now covered in a more generic way.
This would help keeping the public API simple and minimal and avoid confusion caused by having multiple ways to do the same thing.
In particular this PR suggests the following deprecations:
* Deprecate all hard-coded …
=> Deprecate APIs which are now supported in a more generic way or have been renamed

build.sbt
This is a nice little feature of SBT that adds the base URL of the API docs to the metadata in the POM so that projects that depend on Finch can have their own documentation automatically linked to Finch's.
See the [SBT documentation](http://www.scala-sbt.org/0.13/docs/Howto-Scaladoc.html#Define+the+location+of+API+documentation+for+a+library) for more detail.
=> Add API docs URL to POM

docs/request.md
While it might look nice with spaces, it really does not compile.
=> Fix code samples in documentation that do not compile

README.md
Very minor thing, but would help Finch beginners (like me) get started: Httpx isn't imported in the README.md example. I needed to find this class on my own before the example would work. This PR adds an import for it.
=> Add missing Finagle import to example

core/src/main/scala/io/finch/request/package.scala, core/src/test/scala/io/finch/request/HeaderSpec.scala, core/src/test/scala/io/finch/request/OptionalParamSpec.scala, core/src/test/scala/io/finch/request/RequestReaderCompanionSpec.scala
The following behaviour is implemented (required readers are untouched): optional readers read `None` if the underlying string value is empty. Therefore, the _real_ empty string param might be read as
```scala
val e1 = OptionalParam("empty") map { _.getOrElse("") }
val e2 = OptionalParam("empty") withDefault("") // further API
```
=> Fix #171: Empty Strings

build.sbt, demo/src/main/scala/io/finch/demo/Main.scala, demo/src/test/scala/io/finch/demo/DemoSpec.scala
Adding a first simple test to the `demo` app.
To achieve this I had to refactor `App` slightly. It is now broken up in to run-the-thing stuff in `App` and wire-the-things-together in `Demo`. This was necessary due to the `DelayedInit` mixin from `scala.App`.
I also got rid of one wartremover warning by assigning `Await.ready(..` thus returning `Unit` as needed.
=> Added first test to demo

core/src/main/scala/io/finch/request/package.scala, core/src/test/scala/io/finch/request/MultipartParamSpec.scala
This change involves the following:
* `RequiredX` is now `x`, eg. `param("a")`
* `OptionalX` is now `xOption`, eg. `headerOption("X-Secret")`
This naming convention is heavily inspired by Scala standard library, i.e., `head` and `headOption`.
The only one thing doesn't fit well into this approach: `OptionalParams` that return `Seq[String]`. For now, I called it `params0()`. Would be happy to hear feedback and ideas on how can we name optional params.
/cc @jenshalm, @benjumanji, @rpless, @BenWhitehead
=> Fix #187: Reasonable RequestReaders names

.travis.yml, build.sbt, project/build.properties
This is a trivial change but it's kind of cool that you don't need `: _*` for settings now.
=> Update SBT version to 0.13.8 and clean up settings syntax

core/src/main/scala/io/finch/response/package.scala, core/src/test/scala/io/finch/response/ResponseBuilderSpec.scala, docs/index.md, docs/quickstart.md, docs/response.md
The built-in implicit `EncodeResponse` for strings is incorrectly defining the media type to be `plain/text`. This causes some browsers to download the response as a file instead of rendering it on screen. HAProxy is very picky about the media type as well and fails any health check that outputs this value.
This PR fixes the media type to the correct value of `text/plain`.
=> Fix the media type of plain text responses

core/src/main/scala/io/finch/request/LowPriorityRequestReaderImplicits.scala, core/src/main/scala/io/finch/request/package.scala, core/src/test/scala/io/finch/request/DecodeSpec.scala
This is a discussion PR—I don't expect it to be a candidate for merging, and before it becomes one it would need some changes to the docs. This may be a discussion that's been had before, and if so we can just close this.
As I've been working on other stuff in Finch (that I promised to finish up last night :frowning:) I've been finding the `DecodeMagnet` stuff a little noisy, and it's not hard to get rid of if you're willing to make `DecodeRequest` invariant (so that you don't get the compiler trying to serve up instances for `Nothing` in weird places).
I'm personally of the opinion that type classes should be invariant by default, and that anything else should take some justification, in part because of the inference and implicit resolution problems we're seeing here.
Making …
=> Make DecodeRequest invariant and remove DecodeMagnet

core/src/main/scala/io/finch/request/RequestReader.scala, core/src/test/scala/io/finch/request/RequestReaderValidationSpec.scala
As discussed [on gitter](https://gitter.im/finagle/finch?at=553ef441f04b5ab74ce9ce31).
=> Add lift for creating RequestReaders where None represents failure

build.sbt, core/src/main/scala/io/finch/request/RequestReader.scala, core/src/main/scala/io/finch/request/package.scala, core/src/test/scala/io/finch/request/ApplicativeRequestReaderSpec.scala, core/src/test/scala/io/finch/request/RequestReaderValidationSpec.scala, playground/src/main/scala/io/finch/playground/Main.scala
I'm still working on the heterogeneous router, but I wanted to go ahead and post the `RequestReader` changes since they're more straightforward, and since #242 is now broken out into its own issue.
A few points for discussion:
* I'm using Shapeless 2.2.0 even though it's still a release candidate, since the release is likely to happen before 0.7.0 is ready otherwise. The only change that would be necessary (I believe) to go with 2.1 is in the `build.sbt`—before 2.2 plain old `%%` didn't work because `_2.10.4` had to be specified for 2.10.
* I don't see any way to get rid of the boilerplate for `~>` and `~~>` without requiring the types of their arguments to be fully specified, which is annoying. I've provided commented-out generic implementations, but I've left the (modified) …
=> Use Shapeless's HList for request reader composition

.travis.yml, project/plugins.sbt
Minor changes: we don't need to specify the SBT version here, and it probably makes sense to make Coveralls happen separately from the build itself.
=> Clean up Travis CI config

README.md
This is probably too trivial for words, but when coveralls is down (which is often), our badges look like this:
If we switch to [shields.io](http://shields.io/) we could have this:
The fact that the gitter badge is more consistent in size and style with the others is a nice bonus.
=> Use shields.io for slightly more consistent badges

.travis.yml
It looks like we haven't had coverage reports on Coveralls since eab7aa0247d01b4b937010b13637d9ea2cb58e26. sbt-coveralls has been failing on our build because the reports haven't been aggregated, but its been failing silently because it now runs as an `after_script` on TravisCI. This PR aggregates the reports before trying to ship them to Coveralls.
=> Aggregate coverage reports for coveralls

build.sbt
Addresses #259 (thanks, @lderks—I missed the news that the release was out last week). Now that `DecodeRequest` is invariant the upgrade is easy.
I've also updated Shapeless and Jackson to the latest versions.
=> Update versions for Shapeless, Argonaut, and Jackson

README.md, build.sbt, docs/json.md, json4s/README.md, json4s/src/main/scala/io/finch/json4s/package.scala, json4s/src/test/scala/io/finch/json4s/Bar.scala, json4s/src/test/scala/io/finch/json4s/Json4sSpec.scala
We are using json4s in our project since it provides powerful functional API to operate with AST and some neat extensions (mongo objectid, joda date time (de)serialization).
I suppose it would be useful to have this module like an optional one.
=> Json4s encode/decode module implementation

build.sbt
I forgot to do this when we initially bumped sbt-scoverage versions. We no longer need to explicitly disable the CoverallsPlugin on each sub project ( @travisbrown I believe you were looking for this for some other projects).
=> removed disablePlugin from all subprojects

argonaut/src/test/scala/io/finch/argonaut/ArgonautSpec.scala, build.sbt, core/src/main/scala/io/finch/request/package.scala, core/src/main/scala/io/finch/response/package.scala, jackson/src/test/scala/io/finch/jackson/JacksonSpec.scala, json4s/src/test/scala/io/finch/json4s/Json4sSpec.scala, test/src/main/scala/io/finch/test/json/JsonCodecProviderProperties.scala
There's currently a lot of duplication and inconsistency across the tests for the `argonaut`, `json4s`, and `jackson` projects, and the tests that are in place now only validate a few hand-rolled cases. Testing against JSON strings is also fragile, since most libraries don't make guarantees about the order of fields in objects, and since our API doesn't make any guarantees about whitespace (at least I think it doesn't?).
This PR is a quick sketch of some abstractions that allow us to test most (or all) of the functionality of these subprojects in a few lines:
```
"The Argonaut codec provider" should "encode a case class instance as JSON" in encodeFoo
it should "decode a case class instance from JSON" in decodeFoo
it should "encode a list of case class instances as JSON" in encodeFooList …
```
=> Begin to abstract JSON testing tools

build.sbt
Fixes #271. Sorry, that was my fault—didn't realize the JMH plugin would try to instrument classes that didn't have benchmarks in them. Now `sbt demo/run` and `sbt playground/run` both work.
=> Disable JMH plugin for non-benchmark projects with main classes

benchmarks/src/main/scala/io/finch/benchmarks/service/model.scala, benchmarks/src/main/scala/io/finch/benchmarks/service/service.scala, build.sbt, core/src/main/scala/io/finch/request/ToRequest.scala, core/src/main/scala/io/finch/route/EndpointConversions.scala, core/src/main/scala/io/finch/route/Router0.scala, core/src/main/scala/io/finch/route/RouterN.scala, core/src/main/scala/io/finch/route/package.scala, core/src/test/scala/io/finch/route/RouterSpec.scala, demo/src/main/scala/io/finch/demo/Main.scala, demo/src/main/scala/io/finch/demo/endpoint.scala, demo/src/main/scala/io/finch/demo/model.scala, demo/src/main/scala/io/finch/demo/package.scala, demo/src/main/scala/io/finch/demo/service.scala, playground/src/main/scala/io/finch/playground/Main.scala
This is an implementation of coproduct routers as discussed in #270, which this pull request supersedes.
I've also rebased and made some version updates (including to Shapeless 2.2.0 final). Still needs a little cleanup and work on documentation and tests, which I should be able to get to tomorrow (I'm on vacation today).
=> Add coproduct routers

.travis.yml, README.md, project/plugins.sbt
I've been becoming increasingly frustrated with coveralls. It has some uptime issues, doesn't always pick up reports, and the tooling is not great. codecov.io seems to have more features and a really slick browser plugin that integrates coverage data right onto github. It also seems to have taken some initiative on the tooling front and doesn't require you to conform to their api, they transform standard scoverage reports to work in their system (which means we have one less plugin to rely on and thus one less point of failure). I can't speak to the uptime yet because I haven't been using it very long.
I think we should consider moving in a version or two, especially if we keep having issues with coveralls. I'd encourage you to look at [this …
=> Consider using codecov.io instead of coveralls.io

core/src/main/scala/io/finch/route/RouterN.scala, core/src/main/scala/io/finch/route/ToService.scala
This is just a proposal, but moving the `toService` method from enrichment classes to `RouterN` itself via a new type class makes it easier to provide nice error messages. Now instead of this:
```scala
scala> case class X(i: Int)
defined class X
scala> (Get / "foo" /> X(100).toFuture).toService
<console>:28: error: could not find implicit value for parameter folder: shapeless.ops.coproduct.Folder.Aux[io.finch.route.RouterN.EncodeAll.type,shapeless.:+:[com.twitter.util.Future[X],shapeless.CNil],com.twitter.finagle.Service[R,io.finch.HttpResponse]]
(Get / "foo" /> X(100).toFuture).toService
^
```
The user sees this:
```scala
scala> case class X(i: Int)
defined class X
scala> (Get / "foo" /> X(100).toFuture).toService
<console>:28: error: You can only convert a router into a Finagle service …
```
=> Add ToService type class for better error messages

argonaut/src/main/scala/io/finch/argonaut/package.scala, core/src/main/scala/io/finch/response/ResponseBuilder.scala, core/src/main/scala/io/finch/response/package.scala, core/src/test/scala/io/finch/response/EncodeSpec.scala, core/src/test/scala/io/finch/response/ResponseBuilderSpec.scala, core/src/test/scala/io/finch/route/RouterSpec.scala, docs/response.md, jackson/src/main/scala/io/finch/jackson/package.scala, jawn/src/main/scala/io/finch/jawn/package.scala, json/src/main/scala/io/finch/json/package.scala, json4s/src/main/scala/io/finch/json4s/package.scala, test/src/main/scala/io/finch/test/json/JsonCodecProviderProperties.scala
Finch's current `EncodeResponse` implementation imposes HTTP response to be a String. This limitation causes binary content to be encoded as a String. Therefore bytes invalid as UTF-8 string might be silently replaced to other bytes (this behaviour is not specified by the language spec. see [here](http://docs.oracle.com/javase/8/docs/api/java/lang/String.html#String-byte:A-java.lang.String-)). To get rid of this unwanted behaviour, I made these changes:
1. Change `EncodeResponse#apply` to return `Array[Byte]` instead of `String`
2. Now set Content-Type header with `contentType=` instead of `setContentType` because the latter method decides the content to be a text and appends `;charset=utf-8` to the header.
**NOTE:** This is a breaking change since it may affect all the user-defined …
=> Change EncodeResponse to treat response body as Array[Byte]

benchmarks/src/main/scala/io/finch/benchmarks/service/service.scala, demo/src/main/scala/io/finch/demo/endpoint.scala
A recent change from `def` to `val` in the definition of the benchmark deletion service meant the benchmarks weren't running properly (it'd be nice to have this tested). I'm also including a bit of completely unrelated import clean-up.
=> Fix benchmarks and clean up demo imports

core/src/main/scala/io/finch/request/ValidationRule.scala, core/src/main/scala/io/finch/request/package.scala, core/src/main/scala/io/finch/route/package.scala
Also fixes a typo in the name of an implicit def (booleanToMatcher, route package object).
=> Fix #238: move implicit conversion toOptionalRule to ValidationRule companion object

build.sbt
`-Xlint` actually provides "it is not recommended to define classes/objects inside of package objects" warnings (and no other new warnings, at a glance), so we might as well turn it on now that we're moving away from that pattern.
=> Turn on -Xlint

.travis.yml, benchmarks/src/it/scala/io/finch/benchmarks/service/benchmark.scala, build.sbt
This gets the test coverage for finagle-benchmarks up to a reasonable level (and gives us some protection against breaking the benchmarks at the same time). We could still disable coverage reporting for finagle-benchmark (as in #285), but I think I'd vote not to.
=> Add integration tests for service benchmarks

build.sbt
I don't think any of the bug fixes and performance improvements in 2.2.1 affect us, but we might as well update before the 0.7.0 release.
=> Update to Shapeless 2.2.1

benchmarks/src/main/scala/io/finch/benchmarks/service/FinchUserService.scala, build.sbt
A fix for the problem mentioned in #302. I've also changed the `benchmarks` project configuration so that the benchmarks themselves are run with the extra JVM arguments.
=> Fix problem with benchmark service definition

build.sbt
This seems reasonable to me. I'm not sure whether it actually has an effect on the coverage, but it should be a more useful number.
=> Exclude packages that are entirely deprecated from code coverage

core/src/main/scala/io/finch/route/Router.scala, core/src/main/scala/io/finch/route/Smash.scala, core/src/main/scala/io/finch/route/package.scala, core/src/test/scala/io/finch/route/RouterSpec.scala
This addresses #315. `Smash` now handles `HNil` as a special case of `HList`, so `smash[HNil, A] => A` and vice-versa. I also tried to get rid of boilerplate classes `RArrowN` and replaced them with Shapeless `FnToProduct`. Finally, this PR adds a type alias `Router0 = Router[HNil]`.
It's ready to be reviewed.
=> Fix #315: Extend Smash to detect HNils

build.sbt
Shapeless 2.2.2 fixes a binary compatibility issue in 2.2.1 and may also help with dependency resolution problems we're seeing.
=> Upgrade to Shapeless 2.2.2

core/src/main/scala/io/finch/route/Router.scala, core/src/test/scala/io/finch/route/RouterSpec.scala
This simplifies the `:+:` method on routers by adding the smash treatment for coproducts. This means that if we write the following:
```scala
val router = (int :+: string) :+: (string :+: long)
```
We get a `Router[Int :+: String :+: String :+: Long :+: CNil]`, not a router of a nested coproduct. This means that `router.toService` works with the router above.
Before this change you'd have to write the following to accomplish the same thing:
```scala
val router =
(int :+: string).map(_.extendRightBy[String :+: Long :+: CNil]) orElse
(string :+: long).map(_.extendLeftBy[Int :+: String :+: CNil])
```
This PR still needs tests, etc.—I just wanted to put it up for discussion and to address @IgorWolkov's [question on Gitter](https://gitter.im/finagle/finch?at=55800d03f1cd32e97eca8222).
(Note …
=> Simplify disjunction for routers

build.sbt
`NotParsed` currently uses `.getSimpleName` in error strings, which causes "Malformed class name" problems for types defined in the REPL.
We may want to change this eventually, but in the meantime enabling `-Yrepl-class-based` for REPL sessions fixes the issue, and as far as I can tell doesn't break anything (I can run through the examples in [my new hands-on tutorial draft](https://github.com/travisbrown/finch/blob/topic/tutorial/docs/tutorial.md), for example).
=> Use -Yrepl-class-based to avoid getSimpleName errors

core/src/main/scala/io/finch/route/Router.scala
I agree that #337 is reasonable, but this is a quick and easy fix for these instances.
=> Add explicit type parameters to avoid inferring Nothing

benchmarks/src/main/scala/io/finch/benchmarks/service/FinchUserService.scala, core/src/main/scala/io/finch/Endpoint.scala, core/src/main/scala/io/finch/package.scala, core/src/main/scala/io/finch/route/Router.scala, core/src/main/scala/io/finch/route/package.scala, core/src/test/scala/io/finch/route/RouterSpec.scala
As discussed in #320, I just deprecated ```Endpoint``` and ```Endpoint => Service```.
I also replaced ```Endpoint``` with ```Router[Service[Req, Rep]]``` in the demo project.
Hope I did everything right and did't forget anything.
@vkostyukov, please take a look. 
Thanks in advance.
Resolves #320
=> Deprecate all endpoints in favor of coproduct routers

core/src/main/scala/io/finch/route/Mapper.scala, core/src/main/scala/io/finch/route/Router.scala, core/src/test/scala/io/finch/route/RouterSpec.scala
The type class `Mapper` is a variation of "magnet pattern" in Scala that allows us to workaround JVM's type-erasure. This PR introduces an `apply` method on `Router` that accepts a `Mapper` instaince. The compiler will substitute given `Mapper` with either `A => B` or `A => Future[B]`.
The motivation behind this change is to be able to write this:
Before:
```scala
val getUser: Router[User] = get("users" / string) /> { name: String =>
User(name)
}
val patchUser: Router[User] = 
patch("users" / string ? body.as[User]) />> { (name: Stirng, user: User) =>
Future.value(user)
}
```
After:
```scala
val getUser: Router[User] = get("users" / string) { name: String =>
User(name)
}
val patchUser: Router[User] = 
patch("users" / string ? body.as[User]) { (name: Stirng, user: User) => …
```
=> Introduce the Mapper type class

core/src/main/scala/io/finch/route/Mapper.scala, core/src/test/scala/io/finch/route/RouterSpec.scala
A missing bit for #370:
```scala
val hello = get("hello") {
Future.value("Hello, world!")
}
```
=> Allow the Router to be mapped to value/future value

core/src/main/scala/io/finch/route/Mapper.scala, core/src/test/scala/io/finch/route/RouterSpec.scala
I was doing my workshop examples and tried to write a simple web-service that returns the current time. It looks like this:
```scala
def currentTime(): String = Calendar.getInstance().getTime.toString
val time: Router[String] = get(/) { currentTime() }
```
So in order to make it work I made the value argument lazy for `Mapper` (pass by name).
=> Make Mapper lazier

benchmarks/src/it/scala/io/finch/benchmarks/service/UserServiceAppTest.scala, benchmarks/src/main/scala/io/finch/benchmarks/service/circe/benchmark.scala, benchmarks/src/main/scala/io/finch/benchmarks/service/circe/package.scala, build.sbt, circe/README.md, circe/src/main/scala/io/finch/circe/package.scala, circe/src/test/scala/io/finch/circe/CirceSpec.scala
As discussed in #368, I put together a subproject for [jfc](https://github.com/travisbrown/jfc) this weekend, and adding a benchmark ended up taking just a few lines of code.
I don't think we should merge this until we have an 0.1 release for jfc on Maven Central.
At a glance the benchmark looks good but not amazing:
```
[info] Benchmark                                          Mode  Cnt    Score    Error  Units
[info] i.f.b.s.argonaut.ArgonautBenchmark.deleteAllUsers  avgt   20    0.229 ±  0.007  ms/op
[info] i.f.b.s.argonaut.ArgonautBenchmark.getAllUsers     avgt   20   25.448 ±  4.454  ms/op
[info] i.f.b.s.argonaut.ArgonautBenchmark.getUsers        avgt   20  172.193 ±  3.978  ms/op
[info] i.f.b.s.finagle.FinagleBenchmark.deleteAllUsers    avgt   20    0.264 ±  0.017  ms/op
[info] …
```
=> Add support for circe in a subproject

benchmarks/src/main/scala/io/finch/benchmarks/service/FinchUserService.scala, core/src/main/scala/io/finch/Endpoint.scala, core/src/main/scala/io/finch/Endpoints.scala, core/src/main/scala/io/finch/Mapper.scala, core/src/main/scala/io/finch/Outputs.scala, core/src/main/scala/io/finch/ToService.scala, core/src/main/scala/io/finch/package.scala, core/src/main/scala/io/finch/response/EncodeResponse.scala, core/src/test/scala/io/finch/EndpointSpec.scala, petstore/src/main/scala/io/finch/petstore/endpoint.scala
The idea is to allow users to capture the output context while keeping the type information. Previously, this has been done by dropping down to the `Response` type. Now it's possible to use `Output` in order to supply an additional context that will be used while converting an encodeable into a `Response`.
```scala
val postUser: Endpoint[User] = post("users" ? body.as[User]) { u: User =>
Created(u).withHeader("Location" -> u.id)
} 
```
The API of the `Output` completely repeats `ResponseBuilder`, which eventually should be replaced by `Output`.
=> Introduce Endpoint.Output

core/src/main/scala/io/finch/Endpoints.scala, core/src/main/scala/io/finch/request/DecodeRequest.scala, core/src/test/scala/io/finch/EndpointSpec.scala, core/src/test/scala/io/finch/request/RequiredParamSpec.scala
This PR enables UUIDs support in both ways:
* Via `Endpoint` instance `uuid` and `uuids` (tail extractor)
* Via `DecodeRequest` instance for `UUID` type
So the following works as expected.
```scala
val a: Endpoint[UUID] = get("users" / uuid) { id: UUID =>
Ok(id)
}
val b: RequestReader[UUID] = param("id").as[UUID]
```
=> Fix #398: Support UUIDs

core/src/main/scala/io/finch/Endpoint.scala, core/src/test/scala/io/finch/EndpointSpec.scala
This PR is about issue #375. But yet there is a question. 
Due to current `Endpoint` implementation it's type parameter `A` is a type for `Output[A]`. And when you're trying to return different from router applied function's result (look for specs i.e.), you'll get `Endpoint[Any]` at the end, since your handler might return `InternalServerError` just in case:
```scala
val r1: Endpoint[Any] = get(/) { 1/0 } handle {
case e: ArithmeticException => InternalServerError("oh noes")
}
```
I think, there should be better solution. Any ideas?
=> [F-375] Error handler for endpoint

benchmarks/src/main/scala/io/finch/benchmarks/request/reader.scala, benchmarks/src/main/scala/io/finch/benchmarks/service/UserServiceBenchmark.scala, build.sbt, project/plugins.sbt
This PR updates `sbt-jmh` to 0.2.2 as well as well as unifies settings for all the benchmakrs we have.
=> Update sbt-jmh and unify benchmarks

README.md, build.sbt, core/src/main/scala/io/finch/request/package.scala, oauth2/src/main/scala/io/finch/oauth2/package.scala, oauth2/src/test/scala/io/finch/oauth2/OAuth2Spec.scala
This is my first attempt to solve #136.
The API looks as following:
*Authorize*
```scala
val auth: RequestReader[AuthInfo[Int]] = authorize(dataHandler)
val e: Endpoint[Int] = get("user" ? auth) { ai: AuthInfo[Int] =>
Ok(ai.user)
}
```
*Issue Access Token*
```scala
val token: RequestReader[GrangHandlerResult] = issueAccessToken(dataHandler)
val e: Endpoint[String] = get("token" ? token) { ghr: GrantHandlerResult =>
Ok(ghr.accessToken)
}
```
=> Add support for finagle-oauth2

README.md
This is a simple README fix for reference links since they didn't seem to be pointing to the right place.
=> fix some reference links to point at respective homepage

core/src/main/scala/io/finch/Endpoints.scala, core/src/test/scala/io/finch/EndpointSpec.scala
I also moved encoding over to `java.util.Base64` which is now available in Java8.
=> Fix #408: exhaustive match in basicAuth

core/src/main/scala/io/finch/Endpoint.scala, core/src/test/scala/io/finch/EndpointSpec.scala
This PR introduces the `Endpoint.as[A]` method which does the same trick as `RequestReader.as[A]`:
```scala
scala> import io.finch._
import io.finch._
scala> case class Foo(i: Int, s: String)
defined class Foo
scala> val e: Endpoint[Foo] = get(int / string).as[Foo]
e: io.finch.Endpoint[Foo] = GET /:int/:string
```
=> Fix #423: Introduce Endpoint.as[A] method

build.sbt
Will update after circe 0.2.0 is released, which will be shortly after Shapeless 2.3.0 is out. For now I'm just confirming that these updates don't require any changes to source.
=> Update circe to 0.2.0

docs/quickstart.md
* Change the document quickstart.md
* In original document it says server can start via `Http#serve`
* But `Http` object or class in `com.twitter.finagle.httpx` does not have `serve` method.
* After grepping codes, I found it should be `com.twitter.finagle.Httpx`.
=> fix class name which leads user compile error in quickstart.md.

argonaut/src/main/scala/io/finch/argonaut/package.scala, circe/src/main/scala/io/finch/circe/package.scala, core/src/main/scala/io/finch/DecodeRequest.scala, core/src/main/scala/io/finch/ToResponse.scala, core/src/main/scala/io/finch/ToService.scala, core/src/test/scala/io/finch/ApplicativeRequestReaderSpec.scala, core/src/test/scala/io/finch/DecodeSpec.scala, core/src/test/scala/io/finch/EndToEndSpec.scala, json4s/src/main/scala/io/finch/json4s/package.scala
This PR cleans up most of the Finch type classe to use Circe-style patterns (`apply` and `instance`), which I personally really like.
=> Cleanup type-classes

docs/best-practices.md
These must have been copy and `pastedTodo` errors. 
Sorry, I couldn't help myself with that awful joke. :smile:
=> Fix a couple typos in docs/best-practices.md

build.sbt, core/src/test/scala/io/finch/FinchSpec.scala
Hope that's not a surprise by Netty doesn't distinct `x` and `X` headers:
```scala
scala> val rep = Response()
rep: com.twitter.finagle.http.Response = Response("HTTP/1.1 Status(200)")
scala> rep.headerMap.set("X", "y")
res0: com.twitter.finagle.http.HeaderMap = Map(X -> y)
scala> rep.headerMap.set("x", "y")
res1: com.twitter.finagle.http.HeaderMap = Map(x -> y)
scala> rep.headerMap.toMap
res2: scala.collection.immutable.Map[String,String] = Map(x -> y)
scala> rep.headerMap.set("X", "y")
res3: com.twitter.finagle.http.HeaderMap = Map(X -> y)
```
=> Fix flakey test in OutputSpec

build.sbt, core/src/main/scala/io/finch/Endpoint.scala, core/src/main/scala/io/finch/Endpoints.scala, core/src/main/scala/io/finch/Output.scala, core/src/main/scala/io/finch/ToService.scala, core/src/test/scala/io/finch/FinchSpec.scala, oauth2/src/test/scala/io/finch/oauth2/OAuth2Spec.scala
This is just a first step towards Cats in Finch! But I think it's a good start!
This PR uses Cats' `Eval[A]` instead of `() => A`. The end-user API wasn't affected. I'm going to check the benchmarks later tonight and would appriciate any thoughts on this.
=> Use Cats' Eval

argonaut/src/main/scala/io/finch/argonaut/Decoders.scala, argonaut/src/main/scala/io/finch/argonaut/Encoders.scala, argonaut/src/main/scala/io/finch/argonaut/package.scala, circe/src/main/scala/io/finch/circe/Decoders.scala, circe/src/main/scala/io/finch/circe/Encoders.scala, circe/src/main/scala/io/finch/circe/package.scala
This PR allows users to override the default pretty printer for Circe and Argonaut.
Circe:
```scala
import io.finch.circe._
import io.finch.circe.dropNullKeys._
```
Argonaut:
```scala
import io.finch.argonaut._
import io.finch.argonaut.preserveOrder._
```
=> Fix 406: Allow to override pretty printer for Circe and Argonaut

core/src/main/scala/io/finch/Endpoint.scala, core/src/main/scala/io/finch/RequestReader.scala, core/src/main/scala/io/finch/internal/FromParams.scala
Moving `FromParams` under the `io.finch.internal` pacakge.
=> Move FromParams to internal

core/src/main/scala/io/finch/DecodeRequest.scala, core/src/test/scala/io/finch/ApplicativeRequestReaderSpec.scala
This is very silly solution of the weird implicit lookup issue we've recently found.
```scala
scala> case class Foo(s: String)
defined class Foo
scala> param("a").as[Int]
res0: io.finch.RequestReader[Int] = io.finch.RequestReader$$anon$3@39694516
scala> param("a").as[Foo]
res1: io.finch.RequestReader[Foo] = io.finch.RequestReader$$anon$3@73cea421
scala> case class Bar(i: Int)
defined class Bar
scala> param("a").as[Int].as[Bar]
res3: io.finch.RequestReader[Bar] = io.finch.RequestReader$$anon$2@27d3ac40
```
=> Fix #459: DecodeRequest from Generic

benchmarks/src/main/scala/io/finch/benchmarks/service/FinchUserService.scala, core/src/main/scala/io/finch/EncodeResponse.scala, core/src/main/scala/io/finch/Error.scala, core/src/main/scala/io/finch/Output.scala, core/src/main/scala/io/finch/Outputs.scala, core/src/main/scala/io/finch/internal/ToService.scala
This PR allows users to continue using the 0.9.1-style API for failures:
```scala
val error = BadRequest("err" -> "error message")
```
Although, this API is deprecated in favour of `Failure(cause: Exception)`.
=> Add 0.9.1-backward compatible API for failures

core/src/main/scala/io/finch/internal/package.scala
Somehow the new `TooFastString` breaks 2.10 compiler:
```
[error] uncaught exception during compilation: scala.reflect.internal.Types$TypeError
scala.reflect.internal.Types$TypeError: method hexValue$extension in object TooFastString cannot be accessed in object io.finch.internal.package.TooFastString
```
=> Fix weird 2.10 compile error

core/src/main/scala/io/finch/internal/package.scala
Just a couple of simplifications for `TooFastString` to make it work with `00000x` num strings (leading zeros).
=> Simplify TooFastString

benchmarks/src/main/scala/io/finch/benchmarks/BodyBenchmark.scala, core/src/main/scala/io/finch/RequestReaders.scala
There is still a room for improvements, but this is a good step forward: 30% less allocations and 20% better performance (running time) for string-based readers.
```
Before:
[info] BodyBenchmark.byteArray                           avgt   20   614.957 ±   9.786   ns/op
[info] BodyBenchmark.byteArray:·gc.alloc.rate.norm       avgt   20  3408.000 ±   0.001    B/op
[info] BodyBenchmark.byteArrayOption                     avgt   20   516.548 ±  83.328   ns/op
[info] BodyBenchmark.byteArrayOption:·gc.alloc.rate.norm avgt   20  3232.000 ±   0.001    B/op
[info] BodyBenchmark.string                              avgt   20  2933.702 ± 136.387   ns/op
[info] BodyBenchmark.string:·gc.alloc.rate.norm          avgt   20  9836.002 ±  10.691    B/op
[info] BodyBenchmark.stringOption …
```
=> Imporve performance of body readers

build.sbt, core/src/main/scala/io/finch/RequestReaders.scala, core/src/test/scala/io/finch/MultipartParamSpec.scala
This PR fixes #462 by using new Finagle's API for multipars wired lazily to requests.
=> Fix #462: Lazy multipart

build.sbt, core/src/main/scala/io/finch/Error.scala, core/src/main/scala/io/finch/Output.scala, core/src/main/scala/io/finch/Outputs.scala, core/src/main/scala/io/finch/internal/ToService.scala
Remove `Output.Failure(Map[String, String])`.
=> Removed deprecations as per 0.9.3

core/src/main/scala/io/finch/RequestReaders.scala, core/src/test/scala/io/finch/MultipartParamSpec.scala
This is a simple patch that will produce the desired behavior as described in #484. However, the updated code replaces the exception with a `None` value, losing all information about the cause of the error. This seemed reasonable given that Finch is currently using `None` to indicate missing request components; in the future using `Try`, `Either`, or similar may be more useful. Of course, if `com.twitter.finagle.http.Request.multipart` were updated to handle the exceptions directly, this change would no longer be needed.
=> Fix #484: Catch exceptions thrown during multipart parsing

core/src/main/scala/io/finch/internal/ToService.scala
Given that we're already on Finagle 6.31, we don't need that explicit conversion from unhandled exceptions to basic 500s responses.
=> Remove explicit exception handling from ToService

benchmarks/src/main/scala/io/finch/benchmarks/service/FinchUserService.scala, core/src/main/scala/io/finch/Endpoint.scala, core/src/main/scala/io/finch/internal/Mapper.scala, core/src/test/scala/io/finch/EndpointSpec.scala
As discussed [on Gitter](https://gitter.im/finagle/finch?at=566ea5123078c074765111fe), we could use quite reasonable names for `Endpoint.mapX` functions and therby make them public.
=> Make Endpoint.mapX methods public

build.sbt, core/src/main/scala/io/finch/DecodeRequest.scala, core/src/main/scala/io/finch/EncodeResponse.scala, core/src/test/scala/io/finch/DecodeSpec.scala, docs/endpoint.md, docs/json.md, examples/src/main/scala/io/finch/eval/Main.scala, jackson/src/main/scala/io/finch/jackson/package.scala
Still no success in the reproducing the finch-jackson bug so I tried to build a new example (see `eval`) with finch-jakson (including idomatic error handling) to make sure we don't break it.
=> finch-jackson: Clean up *Any* type-classes; Add docs

README.md, core/src/main/scala/io/finch/Endpoint.scala
Finch doesn't really follow the RESTfull patterns, but provides some reasonable abstractions over HTTP services.
=> Clean up RESTful-ness

core/src/main/scala/io/finch/RequestReader.scala
The `rule` string should not contain a final dot because the final dot is added by `NotValid.getMessage`.
=> Remove double dot when using RequestReader.shouldNot

benchmarks/src/main/scala/io/finch/benchmarks/service/FinchUserService.scala, core/src/main/scala/io/finch/DecodeRequest.scala, core/src/main/scala/io/finch/Output.scala, core/src/main/scala/io/finch/Outputs.scala, core/src/main/scala/io/finch/internal/ToService.scala, core/src/test/scala/io/finch/FinchSpec.scala, core/src/test/scala/io/finch/OutputSpec.scala
This is fixes #503 and introduces the third case for `Output` that represents an empty response (no payload). I slightly reworked the implementation and the API according to the Circe's [11th design principle](https://github.com/travisbrown/circe/blob/master/DESIGN.md).
I will let this PR soak here for a couple of days to make sure I'm 100% happy with this solution. Also, I'm going to amend this with backward compatible API.
```scala
scala> Output.empty(Status.Ok)
res0: io.finch.Output[Nothing] = Empty(Meta(Status(200),Map(),List(),None,None))
scala> Output.unit(Status.Ok)
res1: io.finch.Output[Unit] = Empty(Meta(Status(200),Map(),List(),None,None))
scala> Output.payload(100)
res2: io.finch.Output[Int] = Payload(100,Meta(Status(200),Map(),List(),None,None))
scala> Output.failure(new …
```
=> Introduce an empty output

docs/endpoint.md
I got confused by this example yesterday and brought it up in the Gitter chat  room. Discovered these examples were in error and ```/ a / b``` in these examples should be ```/int/int``` so I updated the two examples.
=> Update divOrFail example in endpoint.md

core/src/main/scala/io/finch/RequestReaders.scala, core/src/main/scala/io/finch/internal/ToResponse.scala, core/src/test/scala/io/finch/OutputSpec.scala
As I asked in finagle's Gitter, S3 API needs to support up to 5GB in a single PUT but unfortunately the max chunk size is limited to 2GB by netty so we need streaming to support larger objects. Aside the PUT issue, streaming is required for GETting large objects (that could be uploaded by multipart upload where each transfer is small but could be huge as a result) from the server.
This work is based on @ImLiar 's PoC. https://github.com/finagle/finch/pull/498
Thanks @ImLiar
=> Add streaming request/response

build.sbt, core/src/main/scala/io/finch/internal/ToResponse.scala, examples/src/main/scala/io/finch/streaming/Main.scala
The initial version of streaming example for three types of endpoints:
1. Streaming request
2. Streaming response
3. End-to-end streaming
=> Add streaming example

docs/request.md
I ran into an issue trying to follow the doc for creating a custom decoder for use in a request reader, and updated the doc to show the appropriate function call.  The paragraph following my change may also need an update to be strictly correct, but for now I believe this is an improvement (the old example does not compile under finch-0.9.3 (scala 2.11.7)
=> Custom Decoder doc update

build.sbt, oauth2/src/main/scala/io/finch/oauth2/package.scala
Noticed that oauth2 support should be lazy (evaluating endpoints).
=> finch-oauth2 should be lazy

core/src/main/scala/io/finch/Endpoint.scala, docs/cookbook.md
Deprecating `?` and `::` in this snapshot.
=> Deprecate ? and / and update cookbook

docs/endpoint.md
As someone new to the project, this standard use case for parsing params was non-obvious from the docs and not included in any of the source examples. Adding to help out others exploring or implementing their first endpoints!
=> Adds docs example for parsing params

core/src/main/scala/io/finch/DecodeRequest.scala, core/src/main/scala/io/finch/EncodeResponse.scala, core/src/main/scala/io/finch/internal/Mapper.scala, core/src/main/scala/io/finch/internal/PairJoin.scala, core/src/main/scala/io/finch/internal/ToService.scala
=> Hide prioritization trails and arrange scaladoc comments into groups.

.travis.yml, build.sbt, project/build.properties, project/plugins.sbt
This doesn't include the Finagle update, since I didn't know whether we wanted to publish a new finagle-oauth2 first, but it updates everything else.
=> Update Scala 2.11 and other dependencies and plugins

build.sbt, core/src/test/scala/io/finch/OutputSpec.scala, project/plugins.sbt
Okay, I made a kind of annoying mistake last week.
Last fall I updated circe to sbt-scoverage 1.3.3, ran into [a terrible bug](https://github.com/travisbrown/circe/pull/72) that meant the 2.10 builds weren't running, and then reverted the update back to sbt-scoverage 1.2.0.
Last week I forgot entirely about this, saw that sbt-scoverage 1.3.5 was out, and updated both circe and Finch, without confirming that the bug (https://github.com/scoverage/sbt-scoverage/issues/146) had been fixed. In fact I'd forgotten about the bug entirely.
This means that since 81d89e20bc8c814a95d4aef88ddd956899e6d822 Travis CI hasn't been running 2.10 builds for Finch. Which wouldn't necessarily be a big deal, but some of the new content type stuff doesn't work on 2.10—or rather it works, but requires explicit …
=> Revert sbt-scoverage

core/src/main/scala/io/finch/internal/ToResponse.scala, core/src/main/scala/io/finch/package.scala, examples/src/main/scala/io/finch/streaming/Main.scala
#520 
By the way, it didn't work properly for `Buf` without `Transfer-Encoding: chunked`
=> JSON streaming for `AsyncStream[A]`

docs/json.md
The [json docs](https://github.com/finagle/finch/blob/master/docs/json.md) is missing a backtick.
=> Fix a markdown error (missing backtick) in json docs.

core/src/main/scala/io/finch/internal/FromParams.scala
#574 
I didn't succeed to make it work for all collections using `CanBuildFrom` due to some strange behaviour of implicit resolution and HKT. Tried for a few days, but still failed. Maybe I've missed something, but it just doesn't work for type `T[_]` even if there is an implicit instance of `cbf` in scope.
Anyway, I believe it would be useful even in it's current state. 
If someone could make it in more generic way, it would be super cool.
=> FromParams should be tolerant to optional and seq fields

build.sbt
[Circe 0.4.0-RC1](https://github.com/travisbrown/circe/releases/tag/v0.4.0-RC1) is out!
=> Update Circe to 0.4.0-RC1

benchmarks/src/main/scala/io/finch/benchmarks/FinchBenchmark.scala, build.sbt, core/src/main/scala/io/finch/Endpoint.scala, core/src/main/scala/io/finch/Endpoints.scala, core/src/main/scala/io/finch/Output.scala, core/src/test/scala/io/finch/FinchSpec.scala, oauth2/src/main/scala/io/finch/oauth2/package.scala
Was experimenting with using `Rerunnable[A]` over `Eval[Future[A]]` and I'm quite pleased with the results. Less code, better performance (overall up to 25-35% in terms of allocations and running time improvements):
Pairs: before and after
Matchers and extractors:
```
[info] Benchmark                                              Mode  Cnt      Score       Error   Units
[info] BodyBenchmark.byteArray                                avgt    6   1311.400 ±   620.490   ns/op
[info] BodyBenchmark.byteArray                                avgt    6    570.330 ±    92.477   ns/op
[info] BodyBenchmark.byteArray:·gc.alloc.rate.norm            avgt    6   1872.001 ±     0.001    B/op
[info] BodyBenchmark.byteArray:·gc.alloc.rate.norm            avgt    6   1736.000 ±     0.001    B/op
----
[info] …
```
=> Use Rerunnable

core/src/main/scala/io/finch/Endpoint.scala, core/src/main/scala/io/finch/Endpoints.scala, core/src/main/scala/io/finch/internal/FromParams.scala, core/src/test/scala/io/finch/EndpointSpec.scala, examples/src/main/scala/io/finch/div/Main.scala
As it was discussed earlier: https://github.com/finagle/finch/pull/577#issuecomment-202103686
=> paramsNonEmpty returns NonEmptyList[A]

build.sbt
I'm planning to have circe 0.4.0 out by Monday, and I've tested this locally, but I'm updating to RC2 just in case other people want to try it out with Finch as well.
=> Update circe to second 0.4.0 release candidate

docs/endpoint.md
Docs listed incorrect error type (`io.finch.Error.NoValid`). Also fixed 'should has' typo.
=> io.finch.Error.NoValid => io.finch.Error.NotValid

core/src/main/scala/io/finch/Endpoints.scala, core/src/test/scala/io/finch/BasicAuthSpec.scala, core/src/test/scala/io/finch/FinchSpec.scala, docs/auth.md
We are using finch at a project where we needed a more flexible BasicAuth implementation so we implemented one and I thought of contributing back.
The PR includes two big changes. The first, as per [rfc7235 section 4.1], is to always include a `WWW-Authenticate` header with a 401 Unauthorized response.
[rfc7235 section 4.1]: https://tools.ietf.org/html/rfc7235#section-4.1
The second is to replace the `BasicAuth` parameters by `authenticate: (String, String) => Boolean`. This way it is possible to reuse the same BasicAuth logic and authenticate the credentials by searching a database, reading from a file, or comparing to hard-coded credentials in the code.
Example:
```scala
val basicAuth: BasicAuth = BasicAuth("app-realm") { (user, pass) =>
DB.query[Option[Boolean]](
"SELECT true FROM …
```
=> Flexible Basic Auth

build.sbt, core/src/main/scala/io/finch/Input.scala, core/src/main/scala/io/finch/Output.scala, core/src/test/scala/io/finch/DecodeLaws.scala, core/src/test/scala/io/finch/EncodeLaws.scala, core/src/test/scala/io/finch/EndpointLaws.scala, core/src/test/scala/io/finch/FinchSpec.scala, core/src/test/scala/io/finch/HeaderSpec.scala, core/src/test/scala/io/finch/MissingInstances.scala, core/src/test/scala/io/finch/internal/CaptureLaws.scala
Also updated without issue were finagle and shapeless. the only actual issue encountered was the change in cats dependency on algebra. the net effect was to move Eq from algebra to cats.kernel
=> update cats, circe and catbird dependencies

docs/endpoint.md
Since you have to provide types for each item in the argument tuple of the http verb method (e.g., `get`, `post`), and the error message you get when you try to use, e.g., `ids: List[String]` along with `:: params("ids")` takes a bit of scrutiny to figure out what it wants, I thought an example with the proper type would be helpful to newcomers like me.
Side question: I initially thought "multi-value param" would simply mean 'all the query parameters with that name will be aggregated and their values supplied in a single `Seq[String]`'. But it turns out finch also splits `params`-style query parameters on commas, and filters out empty strings. Which is handy in my current app, but more magical than I would have expected, and I'm not sure how I could get the pre-processed values if I …
=> Add params example and clarify argument type

test/src/main/scala/io/finch/test/ServiceIntegrationSuite.scala, test/src/main/scala/io/finch/test/ServiceSuite.scala
This PR replaces the self type annotation `FlatSpec` by `Suite` in `ServiceSuite` and `ServiceIntegrationSuite` so those can be mixed in with any scalatest specs (`WordSpec`, `FlatSpec`, etc).
=> Replace FlatSpec by Suite in ServiceSuite

argonaut/src/main/scala/io/finch/argonaut/Encoders.scala, circe/src/main/scala/io/finch/circe/Encoders.scala, core/src/main/scala/io/finch/Encode.scala, core/src/main/scala/io/finch/Endpoint.scala, core/src/main/scala/io/finch/Output.scala, core/src/main/scala/io/finch/internal/ToResponse.scala, core/src/main/scala/io/finch/internal/package.scala, core/src/test/scala/io/finch/EncodeLaws.scala, core/src/test/scala/io/finch/EndToEndSpec.scala, core/src/test/scala/io/finch/FinchSpec.scala, core/src/test/scala/io/finch/OutputSpec.scala, examples/src/main/scala/io/finch/eval/Main.scala, jackson/src/main/scala/io/finch/jackson/package.scala, json-test/src/main/scala/io/finch/test/json/JsonCodecProviderProperties.scala, json4s/src/main/scala/io/finch/json4s/package.scala, playjson/src/main/scala/io/finch/playjson/package.scala, sprayjson/src/main/scala/io/finch/sprayjson/package.scala
Once we migrated to content-type-as-a-type, we eliminated the notion of charsets b/c they're a big lie. It's time to bring them back.
The current approach makes it possible to actually apply a charset to an encoder, not only store it in a header. One of the challenges I faced was to pick the default behaviour and stick with it. I decided to go with:
- UTF-8 as a default value passed to an encoder (if not set by a user), as per [rfc6657](https://tools.ietf.org/html/rfc6657)
- If no charset is set on `Output`, none is copied over to an HTTP response
I think those conventions are reasonable enough so they can serve a good foundation to build both text- and binary-based endpoints with Finch.
=> Encoding with charset

core/src/main/scala/io/finch/Output.scala
We probably don't need to set a charset for empty responses.
=> No charset for empty responses

core/src/main/scala/io/finch/Endpoints.scala, core/src/test/scala/io/finch/EndpointSpec.scala
Two commits:
* 590300f to establish previous behavior
* 0f92071 to fix it and test new behavior
I wasn't sure if there was any logic to the order of `it should ...`'s in `EndpointSpec.scala`, so I just put the new test near the other param/params test.
=> Fix #600: Remove querystring params forced comma splitting

core/src/main/scala/io/finch/internal/Mapper.scala, core/src/test/scala/io/finch/EndpointSpec.scala, examples/src/main/scala/io/finch/streaming/Main.scala
I was thinking about proving means that make it easier to return `Response`s from `Endpoint` since it's now an essential way of dealing with multiple content-types. Even though on the long run we have to fix that particular problem and allow multiple content-types, but this doesn't mean there is nothing's left uncovered. So I thought maybe having an established approach from the beginning is a good idea.
This PR makes `Mapper` accept `Response` so it's just less confusing to return that from an `Endpoint`.  Basically, instead of
```scala
val e = get("users" :: string) { s: String =>
val rep = Response(Status.BadRequest)
Future.value(BadResponse(rep))
}
```
We can write:
```scala
val e = get("users" :: string) { s: String =>
Future.value(Response(Status.BadRequest))
}
```
Or even:
```scala …
```
=> Make Mapper accept responses

docs/endpoint.md
Fixes some minor typos or misspellings in endpoints.md.
=> Fix typos in docs/endpoints.md

benchmarks/src/main/scala/io/finch/benchmarks/BodyBenchmark.scala, benchmarks/src/main/scala/io/finch/benchmarks/EndpointBenchmark.scala, benchmarks/src/main/scala/io/finch/benchmarks/ExtractorBenchmark.scala, benchmarks/src/main/scala/io/finch/benchmarks/MatcherBenchmark.scala, core/src/main/scala/io/finch/Endpoint.scala, core/src/main/scala/io/finch/Input.scala, core/src/test/scala/io/finch/BasicAuthSpec.scala, core/src/test/scala/io/finch/BodySpec.scala, core/src/test/scala/io/finch/EndpointSpec.scala, core/src/test/scala/io/finch/FinchSpec.scala, core/src/test/scala/io/finch/HeaderSpec.scala, core/src/test/scala/io/finch/InputSpec.scala, core/src/test/scala/io/finch/ParamSpec.scala, docs/endpoint.md, examples/src/main/scala/io/finch/wrk/Finagle.scala, oauth2/src/test/scala/io/finch/oauth2/OAuth2Spec.scala
This PR makes use of an new `Input` API as well as cleans up an implementation.
=> Use new Input API internally

build.sbt
Circe 0.5.0 is identical to 0.5.0-M3, and Cats 0.7.2 is binary-compatible with 0.7.0, but updating lets us avoid exposing users to [this bug](https://github.com/typelevel/cats/issues/1346) in Cats 0.7.0.
=> Update Cats and Circe versions

benchmarks/src/main/scala/io/finch/benchmarks/BodyBenchmark.scala, core/src/main/scala/io/finch/Input.scala, core/src/test/scala/io/finch/BodySpec.scala, core/src/test/scala/io/finch/InputSpec.scala, docs/endpoint.md, examples/src/main/scala/io/finch/eval/Main.scala, examples/src/test/scala/io/finch/eval/EvalSpec.scala, examples/src/test/scala/io/finch/todo/TodoSpec.scala
I figured since we have this powerful concept of content-type-as-a-type, why not to use it in `withBody` and make it generic? Basically, instead of duplicating logic in `withBody`, `withJson`, `withText`, `withXml`, `withWhatever`, we can just have one.
Before:
```scala
Input.post("/").withBody(Buf.Utf8("text"), Some("text/plain;charset=utf8"))
Input.post("/").withJson(Map("a" -> "b"), Some(Charsets.Utf8))
```
Now:
```scala
// Now:
Input.post("/").withBody[Text.Plain]("text", Some(Charsets.Utf8))
Input.post("/").withBody[Application.Json](Map("a" -> "b"), Some(Charsets.Utf8))
// We get the following for free:
import cats.instances.int._
Input.post("/").withBody[Text.Plain](42)
```
This not only looks nice but also compile-safe: there is no way to make a typo in `Application.Json` (it …
=> Generalize Input.withBody

circe/src/main/scala/io/finch/circe/Decoders.scala
Addresses #647
Ping @vkostyukov
=> Improve decoding errors from finch-circe

README.md, build.sbt, docs/index.md
Finagle-OAuth2: 0.1.7
Circe: 0.5.3
Finagle is still pinned to 6.35 (to stay on 2.10).
=> Prepare the 0.11-M4 release

.travis.yml, build.sbt, core/src/main/scala/io/finch/Encode.scala, core/src/test/scala/io/finch/FinchSpec.scala, core/src/test/scala/io/finch/MissingInstances.scala, oauth2/src/test/scala/io/finch/oauth2/OAuth2Spec.scala, project/build.properties, project/plugins.sbt, test/src/main/scala/io/finch/test/ServiceIntegrationSuite.scala, test/src/main/scala/io/finch/test/ServiceSuite.scala
I'm not sure we want to merge this yet, but I wanted to show that it works. :smile: 
* `Xor` is gone.
* Cats provides its own `UUID` instances.
* ScalaTest has moved a couple of things around.
* `Arbitrary` instances for functions now require `Cogen` instances for the argument types.
I need to take a closer look at the `Cogen` instances, but I think they make sense.
=> Update Cats, circe, ScalaCheck, and ScalaTest versions

build.sbt, core/src/main/scala/io/finch/internal/ToResponse.scala, core/src/main/scala/io/finch/package.scala, docs/cookbook.md, sse/src/main/scala/io/finch/sse/ServerSentEvent.scala, sse/src/test/scala/io/finch/sse/ServerSentEventSpec.scala
Proposed fix for #593 
Adds a ToResponse to create to hook into the asyncBodyResponse
Adds an example of SSE
Adds a section to the cookbook about SSE
Two things to call out:
- This support is very bare-bones and makes it the responsibility of the user to provide properly formatted events
- The [EventSource Standards](https://html.spec.whatwg.org/multipage/comms.html#authoring-notes) advises against using chunked requests, but `asyncResponseBuilder` does use chunked requests. When I tried implementing my own version of `asyncResponseBuilder` that didn't use chunking the `writer` would not write any data into the event. Not sure if it just isn't possible or if there was some method on the writer that I missed that would get it to write.
=> Add basic support for Server Sent Events.

.travis.yml, argonaut/src/test/scala/io/finch/argonaut/ArgonautSpec.scala, benchmarks/src/test/scala/io/finch/benchmarks/EndpointBenchamrkSpec.scala, build.sbt, circe/src/test/scala/io/finch/circe/CirceSpec.scala, core/src/test/scala/io/finch/DecodeEntityLaws.scala, core/src/test/scala/io/finch/EncodeLaws.scala, core/src/test/scala/io/finch/EndpointSpec.scala, core/src/test/scala/io/finch/internal/TooFastStringSpec.scala, examples/src/main/scala/io/finch/eval/Main.scala, examples/src/main/scala/io/finch/oauth2/Main.scala, examples/src/main/scala/io/finch/todo/Main.scala, jackson/src/test/scala/io/finch/jackson/JacksonSpec.scala, json4s/src/test/scala/io/finch/json4s/Json4sSpec.scala, oauth2/src/test/scala/io/finch/oauth2/OAuth2Spec.scala, playjson/src/test/scala/io/finch/playjson/PlayJsonSpec.scala, sprayjson/src/test/scala/io/finch/sprayjson/sprayjsonSpec.scala, sse/src/test/scala/io/finch/sse/ServerSentEventSpec.scala
`sbt validate` allows to run CI script more easily locally.
=> Introduced sbt validate command + fixed scalastyle issues in tests

argonaut/src/main/scala/io/finch/argonaut/Decoders.scala, circe/src/main/scala/io/finch/circe/Decoders.scala, core/src/main/scala/io/finch/internal/package.scala, jackson/src/main/scala/io/finch/jackson/package.scala, playjson/src/main/scala/io/finch/playjson/package.scala, sprayjson/src/main/scala/io/finch/sprayjson/package.scala
Proposed fix for #511. The only thing I was unsure about was whether to use `Buf.ByteArray.Owned` or `Buf.ByteArray.Shared` for the libraries that can convert `Array[Byte]`. I wound up using `Shared`, but I'm not sure this is necessary.
=> Remove String conversion in decoders.

argonaut/src/main/scala/io/finch/argonaut/Encoders.scala, argonaut/src/test/scala/io/finch/argonaut/ArgonautSpec.scala, circe/src/main/scala/io/finch/circe/Encoders.scala, circe/src/test/scala/io/finch/circe/CirceSpec.scala, core/src/main/scala/io/finch/Encode.scala, core/src/test/scala/io/finch/EncodeSpec.scala, core/src/test/scala/io/finch/InputSpec.scala, examples/src/main/scala/io/finch/eval/Main.scala, jackson/src/main/scala/io/finch/jackson/package.scala, jackson/src/test/scala/io/finch/jackson/JacksonSpec.scala, json-test/src/main/scala/io/finch/test/json/JsonCodecProviderProperties.scala, json4s/src/main/scala/io/finch/json4s/package.scala, json4s/src/test/scala/io/finch/json4s/Json4sSpec.scala, playjson/src/main/scala/io/finch/playjson/package.scala, playjson/src/test/scala/io/finch/playjson/PlayJsonSpec.scala, sprayjson/src/main/scala/io/finch/sprayjson/package.scala, sprayjson/src/test/scala/io/finch/sprayjson/sprayjsonSpec.scala
This PR is a successor of #675.
The main goal of this commit is to delegate the process of transforming Exceptions into JSON to the JSON libraries instead of handling it in the core package. Thus JSON Encoder for Exceptions is removed from the core package, but appropriate instances are provided in each of subprojects responsible for integration with the corresponding JSON libraries.
The motivation is that transforming even very simple data structures into the valid JSON is not so trivial and at least involves some logic of escaping strings before inserting them into the JSON document. Also, it seems obvious, that in the situation when exception need to be encoded into JSON, other data should be JSON encoded as well. and user will end up using some JSON library anyway. So, delegating this …
=> Refactor the way how JSON Encoders for Exceptions are provided

argonaut/src/main/scala/io/finch/argonaut/Decoders.scala, circe/src/main/scala/io/finch/circe/Decoders.scala, core/src/main/scala/io/finch/internal/ToResponse.scala, core/src/main/scala/io/finch/internal/package.scala, jackson/src/main/scala/io/finch/jackson/package.scala, playjson/src/main/scala/io/finch/playjson/package.scala, sprayjson/src/main/scala/io/finch/sprayjson/package.scala, sse/src/main/scala/io/finch/sse/ServerSentEvent.scala
Finagle is very close to switching its HTTP implementation over to Netty 4. Let's make sure that Finch will keep working when this happens.
=> Netty-agnostic decoding

benchmarks/src/test/scala/io/finch/benchmarks/EndpointBenchmarkSpec.scala, core/src/main/scala/io/finch/Endpoint.scala, core/src/main/scala/io/finch/Error.scala, core/src/test/scala/io/finch/EndpointSpec.scala, core/src/test/scala/io/finch/ErrorSpec.scala, core/src/test/scala/io/finch/FinchSpec.scala, docs/cookbook.md, docs/endpoint.md
The RequestError class accepts a Seq[Throwable], in case this is empty we should handle this accordingly and print a better message.
=> Increase test coverage of the Error classes

core/src/main/scala/io/finch/Encode.scala
I doubt that instance is useful at all. That should be a responsibility of any of the adopted JSON (or whatever) library to provide this kind of encoding machinery.
=> Remove Encode instance for Either

core/src/main/scala/io/finch/Endpoint.scala, core/src/main/scala/io/finch/internal/package.scala, core/src/test/scala/io/finch/BasicAuthSpec.scala, core/src/test/scala/io/finch/EndpointSpec.scala
I would like us to deprecate `Endpoint.apply` (on the companion object) and provide some explicit meanings for building constant endpoints.
=> Introduce Endpoint.liftX

benchmarks/src/main/scala/io/finch/benchmarks/BodyBenchmark.scala, core/src/main/scala/io/finch/Endpoint.scala, core/src/main/scala/io/finch/Endpoints.scala, core/src/main/scala/io/finch/Error.scala, core/src/main/scala/io/finch/endpoint/Body.scala, core/src/main/scala/io/finch/internal/Rs.scala, core/src/main/scala/io/finch/internal/package.scala, core/src/test/scala/io/finch/BodySpec.scala, core/src/test/scala/io/finch/EndpointSpec.scala, core/src/test/scala/io/finch/data/Foo.scala, examples/src/main/scala/io/finch/eval/Main.scala, examples/src/main/scala/io/finch/oauth2/InMemoryDataHandler.scala, examples/src/main/scala/io/finch/todo/Main.scala, examples/src/main/scala/io/finch/wrk/Finch.scala
This fixes #666.
This is a baby-step improvement that introduces a new way of decoding JSON/XML (anything with `Decode.Aux` instances) in Finch. Instead of using the `.as` machinery which became quite ambiguous already, this RP introduces a new API for building endpoints that read HTTP payloads.
```scala
def body[A, CT <: ContentType]: Endpoint[A]
def bodyOption[A, CT <: ContentType]: Endpoint[Option[A]]
```
The previous version `body.as[A]` is fixed to JSON and is still supported.
I was thinking back and forth on what kind of API would make sense here and decided to go with a very simple thing: just function with two type parameters. Here are some benefits of this approach vs. the previous one (`body.as[A]`).
1. It's less powerful.
2. It reduces the complexity/ambiguity of the `.as` API …
=> Add new body endpoints

argonaut/src/main/scala/io/finch/argonaut/Encoders.scala, circe/src/main/scala/io/finch/circe/Encoders.scala, json-test/src/main/scala/io/finch/test/json/JsonCodecProviderProperties.scala, sprayjson/src/main/scala/io/finch/sprayjson/package.scala
This commit fixes the bug, when exceptions with null messages are failed to be encoded into json by several json libraries supported by finch.
=> Fix json exception encoders

core/src/main/scala/io/finch/Endpoint.scala
after asService...  io.finch.Errors and all io.finch.Error should be handled by default and translated into BadRequest. This adds that behavior for Errors.
=> handle io.finch.Errors

build.sbt
Let's depend on circe-jackson28 and update our own Jackson dependency to be aligned with Finagle 6.40.
=> Update Jackson to 2.8.5

docs/user-guide.md
The function signature and context implies that `DecodeEntity` was intended instead of `Decode`.
=> Fix reference to incorrect decode object

benchmarks/src/main/scala/io/finch/benchmarks.scala, core/src/main/scala/io/finch/Endpoint.scala, core/src/main/scala/io/finch/EndpointResult.scala, core/src/main/scala/io/finch/Endpoints.scala, core/src/main/scala/io/finch/Output.scala, core/src/main/scala/io/finch/endpoint/Body.scala, core/src/main/scala/io/finch/internal/FromParams.scala, core/src/main/scala/io/finch/internal/Rs.scala, core/src/main/scala/io/finch/internal/ToService.scala, core/src/test/scala/io/finch/BasicAuthSpec.scala, core/src/test/scala/io/finch/BodySpec.scala, core/src/test/scala/io/finch/EndpointSpec.scala, core/src/test/scala/io/finch/EntityEndpointLaws.scala, core/src/test/scala/io/finch/FinchSpec.scala, examples/src/test/scala/io/finch/div/DivSpec.scala, examples/src/test/scala/io/finch/eval/EvalSpec.scala, examples/src/test/scala/io/finch/oauth2/OAuth2Spec.scala, examples/src/test/scala/io/finch/streaming/StreamingSpec.scala, examples/src/test/scala/io/finch/todo/TodoSpec.scala, oauth2/src/main/scala/io/finch/oauth2/package.scala, oauth2/src/test/scala/io/finch/oauth2/OAuth2Spec.scala
Currently, `Endpoint`s are backed by `Option[(Input, Rerrunable[Output[A]])]`s. There is nothing wrong with that type and it provides a great insight on what happens in the endpoint, but there is a way to make it 1) simpler and 2) faster.
Let's flatten`Option[Tuple2[_, _]]` into a new type `EndpointResult` (ADT with two cases: matched vs. skipped) and save some allocations on option creations.
In addition to that this PR cleans up a couple of places that I think were poorly structured:
1. All the testing methods on endpoint's result are now explicit (no need for implicit syntax class over the `Option`).
2. All blocking methods are renamed (deprecated) to `awaitX` variants to visually signal the reader that the call is blocking. They also take optional `Duration`, which comes in handy in …
=> Introduce EndpointResult

examples/src/main/scala/io/finch/eval/Main.scala, jackson/src/main/scala/io/finch/jackson/package.scala, jackson/src/test/scala/io/finch/jackson/JacksonSpec.scala
I'm not sure I ever liked the idea of implicit `ObjectMapper` in finch-jackson and given that I'm not sure if that's actually useful, I propose we embed it (object mapper) in finch-jackson.
=> Embed ObjectMapper in finch-jackson

core/src/main/scala/io/finch/Error.scala, core/src/test/scala/io/finch/FinchSpec.scala
The JVM crashes with an InternalError in case a parsing
error is detected in a class that is neated inside two
objects
=> Custom getClass.getSimpleName logic for error handling

benchmarks/src/main/scala/io/finch/benchmarks.scala, circe/src/main/scala/io/finch/circe/Decoders.scala, circe/src/main/scala/io/finch/circe/Encoders.scala, circe/src/main/scala/io/finch/circe/package.scala
As discussed in #676 (and implemented in [Circe 0.7.0-M2](https://github.com/circe/circe/releases/tag/v0.7.0-M2)), encoding should be performed in terms of bytes to avoid extra to-string conversion hence reduce allocations.
New benchmark confirms that printing to bytes directly cuts allocations in half and improves the throughput by ~15-20%.
```
circe-core (string)
[info] Benchmark                                               Mode  Cnt        Score        Error   Units
[info] ToServiceBenchmark.foos                                thrpt   20      463.981 ±     24.913   ops/s
[info] ToServiceBenchmark.foos:·gc.alloc.rate.norm            thrpt   20  5002135.084 ±   3252.704    B/op
[info] ToServiceBenchmark.ints                                thrpt   20     2118.919 ±     49.846   ops/s …
```
=> Encode to ByteBuffer in Circe

build.sbt, core/src/main/scala/io/finch/Endpoint.scala, core/src/main/scala/io/finch/EndpointResult.scala
- Removes deprecations
- Introduces `EndpointResult.output` (the name is available now)
- Bumps version to 0.13-SNAPSHOT
=> Post 0.12 cleanups

docs/user-guide.md
Both auth.md and json.md were removed, so cookbook.md should be next, I guess.
https://github.com/finagle/finch/commit/bcb84a58dbebf38ce9435a321a04da8a05997d3b
https://github.com/finagle/finch/commit/dea22d72509c9a739b42aa2e900e95c89916eacb
=> Fix a broken link in the doc

examples/src/main/scala/io/finch/eval/Main.scala, examples/src/main/scala/io/finch/streaming/Main.scala
Some example programs are not runnable because of the wrong `main` signature.
=> Fix example code

argonaut/src/main/scala/io/finch/argonaut/Decoders.scala, argonaut/src/main/scala/io/finch/argonaut/Encoders.scala, benchmarks/src/main/scala/io/finch/data/Foo.scala, circe/src/main/scala/io/finch/circe/Decoders.scala, circe/src/main/scala/io/finch/circe/Encoders.scala, core/src/main/scala/io/finch/Encode.scala, core/src/main/scala/io/finch/Endpoints.scala, core/src/main/scala/io/finch/internal/package.scala, core/src/test/scala/io/finch/EncodeLaws.scala, core/src/test/scala/io/finch/EncodeSpec.scala, core/src/test/scala/io/finch/EndToEndSpec.scala, core/src/test/scala/io/finch/InputSpec.scala, core/src/test/scala/io/finch/data/Foo.scala, jackson/src/main/scala/io/finch/jackson/package.scala, json-test/src/main/scala/io/finch/test/JsonLaws.scala, json4s/src/main/scala/io/finch/json4s/package.scala, playjson/src/main/scala/io/finch/playjson/package.scala, sprayjson/src/main/scala/io/finch/sprayjson/package.scala, sse/src/main/scala/io/finch/sse/ServerSentEvent.scala, sse/src/test/scala/io/finch/sse/ServerSentEventSpec.scala
- There is a better way to extract string out of the `Buf`.
- It's better to be explicit about converting string into a `Buf`
=> Deprecated BufText

benchmarks/src/main/scala/io/finch/benchmarks.scala, build.sbt, core/src/main/scala/io/finch/Endpoint.scala, core/src/main/scala/io/finch/internal/package.scala, core/src/test/scala/io/finch/EndpointSpec.scala
- Remove deprecated `BufText`.
- Deprecate `|` and `adjoin`. Now there is `product` and `coproduct` (plain types) along with `::` and `:+:` (Shapeless types).
- Bump version to SNAPSHOT.
=> Some cleanups after 0.13

core/src/main/scala/io/finch/internal/currentTime.scala
Today we noticed one of our HTTP clients logging a warning about our Finch services responding with an invalid Date header. The Date in question looked like `Thu, 2 Mar 2017 01:47:19 GMT`. As it turns out this is invalid according to [RFC 7231](https://tools.ietf.org/html/rfc7231#section-7.1.1.1) (and also RFC 2616, but this was made obsolete by 7231). The problem is that the day of the month must be 2 digits. So the date should actually be `Thu, 02 Mar 2017 01:47:19 GMT`.
This change uses an explicit `DateTimeFormatter` pattern and uses a time zone of GMT to adhere to the spec. I could not find a way to make `DateTimeFormatter.RFC_1123_DATE_TIME` to pad the day of the month field, but if anyone knows of way I think that would better. Let me know what you think.
For reference:
The …
=> Fix Date Header to conform to RFCs 7231 and 5322

build.sbt
This PR fixes the `Finagle server without metrics` warning when running the example Todo app. The warning is displayed when navigating to the admin dashboard. The `twitter-server` lint rule is defined [here](https://github.com/twitter/twitter-server/blob/master/src/main/scala/com/twitter/server/lint/NullStatsReceiversRule.scala#L22) and requires you have the finagle-stats jar on your classpath (see details [here](https://twitter.github.io/twitter-server/Features.html#metrics)).
=> Add finagle-stats dependency to examples proj

build.sbt, core/src/main/scala/io/finch/Endpoint.scala, generic/src/main/scala/io/finch/generic/FromParams.scala, generic/src/main/scala/io/finch/generic/GenericDerivation.scala, generic/src/main/scala/io/finch/generic/package.scala, generic/src/test/scala/io/finch/generic/DerivedEndpointLaws.scala, generic/src/test/scala/io/finch/generic/GenericSpec.scala
Before:
```
import io.finch._
val e = Endpoint.derive[Foo].fromParams
```
After:
```
import io.finch._
import io.finch.generic_
val e = deriveFor[Foo].fromParams
```
Resolves #528
=> Introduce finch-generic module

core/src/main/scala/io/finch/Endpoint.scala, core/src/main/scala/io/finch/Endpoints.scala, core/src/main/scala/io/finch/Input.scala, core/src/main/scala/io/finch/internal/ToService.scala, core/src/test/scala/io/finch/BodySpec.scala, core/src/test/scala/io/finch/EndpointSpec.scala, core/src/test/scala/io/finch/FinchSpec.scala, core/src/test/scala/io/finch/InputSpec.scala
While `Input` was always a case class it wasn't fully immutable given all the `withX` methods mutated the underlying (also mutable) Finagle's request. This PR makes it actually immutable by copying the request each time it's mutated.
In addition to that, I also decided to rebrand `Input.path` to `Input.route` to clearly distinguish it from `Request.path` and state that it's used with the matching/routing endpoints.
=> Make Input actually immutable

core/src/main/scala/io/finch/Endpoint.scala, core/src/main/scala/io/finch/Endpoints.scala, core/src/main/scala/io/finch/endpoint/fileUpload.scala, core/src/main/scala/io/finch/package.scala, core/src/main/scala/io/finch/syntax/EndpointMapper.scala, core/src/main/scala/io/finch/syntax/EndpointMappers.scala, core/src/main/scala/io/finch/syntax/Mapper.scala, core/src/main/scala/io/finch/syntax/package.scala, core/src/test/scala/io/finch/EndpointSpec.scala
This PR decouples `Endpoint` from `Mapper` and is the first step towards dedicated "syntax" layer (as per #637).
Right now `Mapper` is coupled with every method-matching endpoint such that the most common pattern (i.e., `get(/)(mapper)`) still works/compiles. At this point, "syntax" is available by default (from the `io.finch._` import) but the plan is to make it explicit under `io.finch.syntax._` in the next releases (we have to think whether we need to provide a non-syntax way of matching methods).
=> Decouple Endpoint from Mapper (syntax)

examples/src/main/scala/io/finch/wrk/Finagle.scala
It hardly has any effect on performance.
* Before:
* Run 1: Requests/sec:  17725.24
* Run 3: Requests/sec:  34056.66
* After:
* Run 1: Requests/sec:  14805.84
* Run 3: Requests/sec:  34134.74
=> Make Finagle in benchmark use Date header

core/src/main/scala/io/finch/endpoint/body.scala, core/src/test/scala/io/finch/BodySpec.scala, core/src/test/scala/io/finch/EndpointSpec.scala, core/src/test/scala/io/finch/data/Foo.scala
=> Uniformly treat zero-length bodies as missing

core/src/main/scala/io/finch/Bootstrap.scala, core/src/main/scala/io/finch/Endpoint.scala, core/src/main/scala/io/finch/internal/ToService.scala, core/src/test/scala/io/finch/EndpointSpec.scala
This suppresses #583 and fixes #575.
The idea is pretty much the same. Here is the syntax example based on our TE benchmark:
```scala
val service = Bootstrap
.serve[Application.Json](json)
.serve[Text.Plain](plaintext)
.toService
```
The reason I decided to call it `Bootstrap` is that I believe we would be able to add more machinery to it so users can configure a bunch of other things in their derived services. Examples:
- Report stats per endpoint (into a given stats receiver), see #781 
- Enable responding 405, see #784 
This new `Bootstrap` type can also act as a config for our existing features. For example, we might think of providing a way to disable the `Date` header, supplied by default. Something along the lines (just using the case class `copy` method, somewhat close to what …
=> Introduce Bootstrap

benchmarks/src/main/scala/io/finch/benchmarks.scala, core/src/main/scala/io/finch/internal/ParseNumber.scala, core/src/main/scala/io/finch/internal/package.scala
With the cost of slightly more code we can achieve better throughput (and fewer allocations):
```
NEW:
[info] Benchmark                                             Mode  Cnt    Score     Error   Units
[info] TooFastStringBenchmark.someInt                        avgt   10   13.562 ±   0.606   ns/op
[info] TooFastStringBenchmark.someInt:·gc.alloc.rate.norm    avgt   10   16.000 ±   0.001    B/op
OLD:
[info] Benchmark                                             Mode  Cnt     Score     Error   Units
[info] TooFastStringBenchmark.someInt                        avgt   10    15.586 ±   0.639   ns/op
[info] TooFastStringBenchmark.someInt:·gc.alloc.rate.norm    avgt   10    40.000 ±   0.001    B/op
```
=> Introduce ParseNumber

core/src/main/scala/io/finch/Bootstrap.scala, core/src/main/scala/io/finch/ToService.scala, core/src/test/scala/io/finch/BootstrapSpec.scala, core/src/test/scala/io/finch/ToResponseSpec.scala
The `copy` method generated for a case class isn't necessarily what we need. It makes it much easier to drop the `CTS <: HNil` type given it doesn't have a corresponding argument. I downgraded  `Bootstrap` to a regular class and supplied our own copy (`configure` in that case). This way we distinct two copy operations on the `Bootstrap`:
- modifying endpoints via `serve` (takes care of types)
- modifying one of the configuration params via `configure`(doesn't care about types)
=> Fix Bootstrap.copy() bug

core/src/main/scala/io/finch/Endpoint.scala, core/src/main/scala/io/finch/Output.scala, core/src/test/scala/io/finch/FinchSpec.scala, core/src/test/scala/io/finch/OutputSpec.scala
Applying some technics I learned from @fwbrasil.
The biggest thing is to avoid closure allocations by embedding a `Funciton1` or `Function2` into an enclosing scope/object. This played really nicely in the `Endpoint` (see performance results bellow).
In addition to that optimization I also restructured the `Output` type a bit:
- Got rid of `Meta` and merged its members into each object
- Added `traverseFlatten` (a specialised and cheap version of `traverse().flatten`)
- Added `withHeaders` and `withCookies` that allow copying all things in one shot (no need to allocate an intermediate `Output` for each header).
In a nutshell
- `map*` operations are now up to **40% faster** (400 bytes fewer allocations on each call)
- `::` is now up to **5% faster** (120 bytes fewer allocations on each …
=> Optimize Endpoint and Output

docs/src/main/tut/user-guide.md
modify bodyString to stringBody
I was very confused because of bodyString.
I could find stringBody instead of bodyString in io.finch.endpoint.Bodies.
=> fix a wrong attribute name in user-guide.md

build.sbt, docs/src/main/tut/user-guide.md
Under Scala 2.12 `-Xlint` brings in some features of `-Xwarn-unused-imports` and this causes Tut to output these warnings in the docs. This removes `-Xlint` from the docs build only and fixes the #827. We may want to try to re-enable the other features of `-Xlint` at some point. 
Also fixed a couple compilation issues in the Enumerator docs.
Also @vkostyukov do you just run `sbt publishMicrosite` to push the docs to github pages or do you have another work flow?
=> Fix docs build outputting 'unused import' for every import

core/src/main/scala/io/finch/endpoint/cookie.scala
I noticed that `Cookie`'s `toString` prints `param` to the string instead of `cookie` while working on some on Endpoint ADTs. Figured it better to fix separately.
=> Fix Cookie#toString displaying 'param' and instead show 'cookie.

docs/src/main/tut/cookbook.md
Updated example to use value classes similar to the example found at https://twitter.github.io/util/guide/util-cookbook/futures.html.
=> Update docs to use value classes in Future conversion example.

core/src/test/scala/io/finch/syntax/MapperSyntaxSpec.scala
Eventually, scalacheck passed `/` (right when it was merged to master) as an argument to `Input.get`.
Replaced `string` with `int` to prevent such situation.
=> Replace string with int as test input for MapperSyntaxSpec

core/src/main/scala/io/finch/syntax/ToTwitterFuture.scala, core/src/main/scala/io/finch/syntax/scala/ScalaToTwitterFuture.scala, core/src/main/scala/io/finch/syntax/scala/package.scala
This allows to enable all syntax (including methods `get`, `post`, etc) by just importing `io.finch.syntax.scala._` (no need for `io.finch.syntax._` import).
@ImLiar Please, take a look.
=> Enable all syntax in io.finch.syntax.scala._

core/src/main/scala/io/finch/endpoint/path.scala
`path[Long]` -> `path[String]` for `string`
=> typo fix in ScalaDoc

docs/src/main/tut/cookbook.md
Example 5 in the Finch cookbook (https://finagle.github.io/finch/cookbook.html) shows how to extract headers from a request, but the Input doesn't call the set-up endpoint, which results in
```
res31: Option[String] = None
```
The desired behaviour is to show that the headers are indeed extracted.
```scala
res1: Option[String] = Some(Headers: Map(foo -> bar))
```
=> Call /hello endpoint in cookbook example 5

.travis.yml, build.sbt, project/build.properties
- Use sbt 0.13.16 (https://github.com/sbt/sbt/releases/tag/v0.13.16)
- Compile against scala 2.12.3 and update travis-ci accordingly
- scalatest 3.0.3 -> 3.0.4 (http://www.scalatest.org/release_notes/3.0.4)
- play 2.6.3 -> 2.6.6 (https://www.playframework.com/changelog)
- discipline 0.7.3 -> 0.8 (compiled against 2.12.2 instead of 2.12.0-RC1, https://github.com/typelevel/discipline/compare/v0.7...v0.8)
=> Update third-party dependencies

.travis.yml, build.sbt, circe/src/main/scala/io/finch/circe/Decoders.scala, docs/src/main/tut/user-guide.md, json-test/src/main/scala/io/finch/test/JsonLaws.scala
This gets us on Cats 1.0.0-RC1 with the newly published [iteratee.io 0.15.0](https://github.com/travisbrown/iteratee/releases/tag/v0.15.0).
=> Update to iteratee.io 0.15.0 and Cats 1.0.0-RC1

core/src/main/scala/io/finch/syntax/scala/CallingThreadExecutionContext.scala, core/src/main/scala/io/finch/syntax/scala/ScalaToTwitterFuture.scala
By using a custom CallingThreadExecutionContext we can save a trip through the thread pool and two context switches.
This is an optimization that Twitter Future does by default, but for Scala Future this needs to be done manually (where appropriate).
I've also made ScalaToTwitterFuture a lazy val instead of a def, for a decrease in garbage creation and increase in performance.
(I've noticed that there seem to be quite a few other places in Finch where this might make sense.)
This leads to a significant increase in performance in a simple benchmark of an Endpoint returning `scala.concurrent.Future.successful { Ok() }` :
```
scala.concurrent.ExecutionContext.Implicits.global:
Running 30s test @ http://127.0.0.1:8080/health
6 threads and 6 connections
Thread Stats   Avg      Stdev     Max …
```
=> Optimize Scala Future -> Twitter Future conversion

circe/src/main/scala/io/finch/circe/package.scala, circe/src/test/scala/io/finch/circe/test/CirceSpec.scala
See details in the Circe's PR: https://github.com/circe/circe/pull/739
Our `ToService` benchmark looks pretty great yet I'm unable to reproduce the numbers in the wrk. Let's consider this an experimental until we know more about the performance improvements.
```
PREDICT SIZE DISABLED:
[info] Benchmark                                               Mode  Cnt       Score       Error   Units
[info] ToServiceBenchmark.foos                                thrpt   10   13876.850 ±  9207.359   ops/s
[info] ToServiceBenchmark.foos:·gc.alloc.rate.norm            thrpt   10  111100.167 ±  2415.956    B/op
[info] ToServiceBenchmark.ints                                thrpt   10   76738.704 ±  4821.128   ops/s
[info] ToServiceBenchmark.ints:·gc.alloc.rate.norm            thrpt   10   23449.304 ± …
```
=> Add Circe's predict size support

core/src/main/scala/io/finch/Endpoint.scala
I think it makes sens to deprecate
- `withHeader`, `withCharset`, etc as they may not be that popular
- `liftFuture` and `liftFutureOutput` in favour of `async` equivalents to make them symmetric with `map*` functions.
=> Deprecate some methods

core/src/main/scala/io/finch/endpoint/multipart.scala, core/src/test/scala/io/finch/MultipartSpec.scala, docs/src/main/tut/user-guide.md
Adds an endpoint fileUploads(paramName). As mentioned in gitter, this is useful for us.
A suggestion would be to maintain only APIs for multiple file uploads, essentially replacing fileUpload and fileUploadOption (one FileUpload) with fileUploads and fileUploadsOption (Seq[FileUpload]) as the latter also represent the former. If you want I can do this.
=> Multiple file uploads

core/src/main/scala/io/finch/endpoint/multipart.scala, core/src/test/scala/io/finch/MultipartSpec.scala, docs/src/main/tut/user-guide.md
This introduces `multipartAttributes` and `multipartAttributesNel`.
=> Support multiple attributes

core/src/main/scala/io/finch/package.scala, core/src/main/scala/io/finch/syntax/DeprecatedEndpointMappers.scala
Addressing #833.
Opinions on other ways to achieve this are more than welcome!
```scala
scala> import io.finch._
import io.finch._
scala> val p = get(/) { Ok("foo") }
val p = get(/) { Ok("foo") }
<console>:14: warning: method get in trait DeprecatedEndpointMappers is deprecated (since 0.16): Enable syntax explicitly: import io.finch.syntax._
val p = get(/) { Ok("foo") }
^
p: io.finch.Endpoint[String] = GET /
scala> import io.finch.syntax._
import io.finch.syntax._
scala> val p = get(/) { Ok("foo") }
val p = get(/) { Ok("foo") }
p: io.finch.Endpoint[String] = GET /
```
=> Deprecate implicit syntax

circe/src/main/scala/io/finch/circe/AccumulatingDecoders.scala, circe/src/main/scala/io/finch/circe/Encoders.scala, circe/src/main/scala/io/finch/circe/package.scala, circe/src/test/scala/io/finch/circe/test/CirceSpec.scala
This one addresses https://github.com/finagle/finch/issues/587
To enable accumulating decoding one should use `import io.finch.circe.accumulating._` instead of `import io.finch.circe._`.
🎄🎁
=> Add accumulating option to io.finch.circe

build.sbt
Right now the code fences in the docs are filled with `warning: Unused import`. This due to how tut uses the REPL to evaluate code. For now we can filter out `-Ywarn-unused-import` in the docs project. One downside is that we won't get these errors now for the docs, but I think we'll just have to live with it. We'll also need to republish the docs after this.
=> Remove '-Ywarn-unused-import' from docs project's scalacOptions 

docs/src/main/tut/user-guide.md
Reading the documentation, I stumbled upon a strange example in the Match Verb section. To be precise, It didn't give any examples of matching verbs.
This PR reflects the way I understand what should be there, but I'm not sure if this is exactly what author wanted to show.
=> Fix example for the match verbs section of the documentation

README.md
Currently, the example errors on compilation with:
```
[error] reference to get is ambiguous
[error] it is imported twice in the same scope by
[error] import io.finch.syntax._
[error] and import io.finch._
```
I also updated the versions in the README so that folks will be directed to the latest version of Finch.
=> Fix Hello World example and update versions

core/src/main/scala/io/finch/Accept.scala, core/src/main/scala/io/finch/Bootstrap.scala, core/src/main/scala/io/finch/NegotiateToResponse.scala, core/src/main/scala/io/finch/ToService.scala, core/src/test/scala/io/finch/FinchSpec.scala, core/src/test/scala/io/finch/NegotiateToResponseSpec.scala
To follow up on #905. This PR 
- adds some sacladoc for `Bootstrap`
- Rebrands `Eq[Accept]` instance to just `Accept.matches` method
- Renames `Accept.apply` to `Accept.fromString` and gives up on options
=> Add docs for bootstrap

benchmarks/src/main/scala/io/finch/benchmarks.scala, benchmarks/src/main/scala/io/finch/data/Foo.scala
We don't really need a separate benchmark for ToService as it still delegates to `Bootstrap`. Here is the initial results:
```
[info] JsonAndTextNegotiatedBootstrapBenchmark.foos                                thrpt   10   29488.779 ±  2146.953   ops/s
[info] JsonAndTextNegotiatedBootstrapBenchmark.foos:·gc.alloc.rate.norm            thrpt   10   80254.923 ±   270.207    B/op
[info] JsonBootstrapBenchmark.foos                                                 thrpt   10   22546.634 ±   980.536   ops/s
[info] JsonBootstrapBenchmark.foos:·gc.alloc.rate.norm                             thrpt   10  110968.068 ±  2435.075    B/op
[info] JsonNegotiatedBootstrapBenchmark.foos                                       thrpt   10   21366.940 ±  1125.327   ops/s
[info] …
```
=> Unify ToService and Bootstrap benchmarks

core/src/main/scala/io/finch/Accept.scala, core/src/main/scala/io/finch/NegotiateToResponse.scala, core/src/main/scala/io/finch/ToService.scala
Several things going on here:
- `Accept.fromString` now parses string directly (w/o use of the `MimeType` API)
- New type-class `Accept.Matcher` allows mapping existing content-types (i.e., JSON, text) onto corresponding `Accept` instances so we don't have to create/allocate those for each part of a coproduct.
- This new type-class surely complicates things a bit but I think it models the matching more fairly as we shouldn't be parsing Accept headers from content-type values in the first place. Now there is a distinction.
@ImLiar @rpless Mind taking a quick look?
=> Cheaper Accept

circe/src/main/scala/io/finch/circe/package.scala
Let's deprecate it and remove it in 0.18 (see #891).
=> Deprecated Circe's jackson serializer

core/src/main/scala/io/finch/endpoint/path.scala, core/src/test/scala/io/finch/ExtractPathLaws.scala
Addresses https://github.com/finagle/finch/issues/902
Though I suppose that use of a netty-provided solution in a long-run might be not the best pick, it solves the problem and does it _very_ efficiently.
See https://github.com/netty/netty/blob/d672a5a483d0c919279dc9d9724011b6d9dcfd9f/codec-http/src/main/java/io/netty/handler/codec/http/QueryStringDecoder.java#L290)
=> Add path decoding for path[String]

core/src/main/scala/io/finch/ToResponse.scala
This disentangles the `Coproduct` induction logic in `ToResponse`
derivation from the actual encoding of values.
The net result is greatly reduced compilation times for large
`Coproducts`.
Fixes #923
=> Use a dedicated typeclass to guide coproduct induction

core/src/main/scala/io/finch/Bootstrap.scala, core/src/main/scala/io/finch/Endpoint.scala, core/src/main/scala/io/finch/EndpointResult.scala, core/src/main/scala/io/finch/ToService.scala, core/src/main/scala/io/finch/endpoint/body.scala, core/src/main/scala/io/finch/endpoint/header.scala, core/src/main/scala/io/finch/endpoint/multipart.scala, core/src/main/scala/io/finch/endpoint/param.scala, core/src/main/scala/io/finch/endpoint/path.scala, core/src/main/scala/io/finch/syntax/EndpointMapper.scala, core/src/test/scala/io/finch/BootstrapSpec.scala, core/src/test/scala/io/finch/EndpointSpec.scala, iteratee/src/main/scala/io/finch/iteratee/package.scala, iteratee/src/test/scala/io/finch/iteratee/EnumerateEndpointSpec.scala
This is essentially an iteration on #883 that instead of capturing a matched method as part of `Input`, introduces a new `EndpointResult` case. I like this approach better because:
- It's compliant with https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html (10.4.6)
- It's more efficient (`Input` remains skinner)
- It keeps a reasonable semantic for `Endpoint.apply(Input)` for endpoint-mappers so REPL/test environments will return "not-matched" when HTTP verb is different.
Example:
```scala
scala> val a = get("foo") { Ok("foo") }
a: io.finch.Endpoint[String] = GET /foo
scala> val b = post("foo") { Ok("post foo") }
b: io.finch.Endpoint[String] = POST /foo
scala> val c = put("foo") { Ok("put foo") }
c: io.finch.Endpoint[String] = PUT /foo
scala> val s = …
```
=> Support MethodNotAllowed via new EndpointResult

core/src/main/scala/io/finch/endpoint/header.scala, core/src/main/scala/io/finch/internal/Rs.scala
ran `sbt -J-XX:MaxMetaspaceSize=1G test`.
=> Add headerNotParse function to Rs

core/src/main/scala/io/finch/Output.scala, core/src/test/scala/io/finch/FinchSpec.scala, core/src/test/scala/io/finch/OutputSpec.scala
Chunked plain text reponses would not include the `charset` part of the `Content-Type` header.
```
val dummy: Endpoint[AsyncStream[String]] = get("dummy"){
Ok( AsyncStream.of("Hello / Привет")).withCharset(StandardCharsets.UTF_8)
}
``` 
The response of this endpoint would be correctly encoded in UTF-8, but the browsers would interpret it wrongly becuase of the missing charset part in the response header.
=> set charset in the Content-Type header for chunked responses

benchmarks/src/main/scala/io/finch/benchmarks.scala, core/src/main/scala/io/finch/Input.scala, core/src/test/scala/io/finch/InputSpec.scala
Addresses #942.
Benchmark results look promising:
```
BEFORE:
[info] Benchmark                                                   Mode  Cnt     Score     Error   Units
[info] InputBenchmark.fromEmptyPath                                avgt   10   165.508 ±  12.205   ns/op
[info] InputBenchmark.fromEmptyPath:·gc.alloc.rate.norm            avgt   10   280.000 ±   0.001    B/op
[info] InputBenchmark.fromPath                                     avgt   10   418.471 ±  10.846   ns/op
[info] InputBenchmark.fromPath:·gc.alloc.rate.norm                 avgt   10   664.000 ±   0.001    B/op
AFTER:
[info] Benchmark                                                   Mode  Cnt     Score     Error   Units
[info] InputBenchmark.fromEmptyPath                                avgt   10    14.236 ±   0.297 …
```
=> Faster route parsing

build.sbt, docs/src/main/tut/user-guide.md, refined/src/main/scala/io/finch/refined/PredicateFailed.scala, refined/src/main/scala/io/finch/refined/package.scala, refined/src/test/scala/io/finch/refined/DecodeEntityRefinedSpec.scala, refined/src/test/scala/io/finch/refined/DecodePathRefinedSpec.scala, refined/src/test/scala/io/finch/refined/PredicateFailedSpec.scala
This PR enables support for [refined](https://github.com/fthomas/refined) types in query parameters, path segments, and other request entities.
Personally, I find it very handy for validation on the type level. This library is also supported by 
circe, so users are able to use refined types in DTOs along with JSON decoders, but it's optional.
=> Add finch-refined module with refined types support

benchmarks/src/main/scala/io/finch/benchmarks.scala, core/src/main/scala/io/finch/endpoint/body.scala, core/src/main/scala/io/finch/internal/package.scala, core/src/test/scala/io/finch/internal/HttpMessageSpec.scala
This little method is being called on each `body` decode and it's now 4x faster.
```
Benchmark                                                        Mode  Cnt    Score     Error   Units
HttpMessageBenchmark.fastChartset                                avgt   10   79.129 ±   5.363   ns/op
HttpMessageBenchmark.fastChartset:·gc.alloc.rate.norm            avgt   10   72.000 ±   0.001    B/op
HttpMessageBenchmark.slowCharset                                 avgt   10  290.393 ± 125.117   ns/op
HttpMessageBenchmark.slowCharset:·gc.alloc.rate.norm             avgt   10  372.000 ±  19.124    B/op
```
=> Optimize charsetOrUtf8

core/src/main/scala/io/finch/Endpoint.scala, core/src/main/scala/io/finch/EndpointResult.scala, core/src/main/scala/io/finch/Endpoints.scala, core/src/main/scala/io/finch/ToService.scala, core/src/main/scala/io/finch/Trace.scala, core/src/main/scala/io/finch/endpoint/body.scala, core/src/main/scala/io/finch/endpoint/cookie.scala, core/src/main/scala/io/finch/endpoint/header.scala, core/src/main/scala/io/finch/endpoint/multipart.scala, core/src/main/scala/io/finch/endpoint/param.scala, core/src/main/scala/io/finch/endpoint/path.scala, core/src/main/scala/io/finch/syntax/EndpointMapper.scala, core/src/test/scala/io/finch/FinchSpec.scala, core/src/test/scala/io/finch/TraceSpec.scala, iteratee/src/main/scala/io/finch/iteratee/package.scala
We've been talking quite a bit about the ways to provide users with a context of what endpoint was actually matched (see #953 for a top-level issue). This wasn't possible today.
Both of our attempts to built-in metrics/telemetry failed because of that (see #845 and #855) as we didn't have the right tools to implement it.
I've been playing with the idea of including the matched path into an `EndpointResult` so it could be propagated along the request/input path. This way, at the very bottom (in `ToService`) we can extract this matched path and do something useful with that, for example, report metrics.
This PR [RFC] introduces a new concept `io.finch.Trace` that represent a matched path of an endpoint and is optimized for low footprint and fast concat. Right now, we aren't doing anything …
=> Introduce Trace (what endpoint was matched) [RFC]

core/src/main/scala/io/finch/Decode.scala, core/src/main/scala/io/finch/endpoint/body.scala, core/src/test/scala/io/finch/BodySpec.scala, core/src/test/scala/io/finch/data/Foo.scala, docs/src/main/tut/user-guide.md
https://github.com/finagle/finch/issues/958
- Add new abstraction `AdaptableDecode` that is used only for `body` and all the related endpoints. This abstraction enables coproduct support for `Content-Type`:
```scala
body[A, Application.Json :+: Application.Csv :+: CNil]
```
Backward-compatibility is there with a very small overhead of one more instance per call.
- Add specs and related documentation
=> Add support for content-type-based decoding of request body

build.sbt, refined/src/main/scala/io/finch/refined/package.scala
I just noticed that the new `finch-refined` module wasn't being published.
```
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: com.github.finagle#finch-refined_2.12;0.22.0: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
```
=> Aggregate refined

docs/src/main/tut/user-guide.md
Makes the Circe Exception Encoder handle accumulated errors. 
Also the docs failing to compile with `docs/makeMicrosite` something about importing `Person._` was breaking them. I pulled those codecs out of the companion object to get it to compile. I'm open to alternatives for fixing that.
=> Update example to support both Finch and Circe accumulated errors

build.sbt
We're ready to release the standard artifacts (`Rurunnable`).
I will cut an arrows release when they are out (see https://github.com/traneio/arrows/pull/11).
=> Preparing the 0.23 release

core/src/main/scala/io/finch/Bootstrap.scala, core/src/main/scala/io/finch/Decode.scala, core/src/main/scala/io/finch/ToService.scala, core/src/main/scala/io/finch/endpoint/body.scala, core/src/main/scala/io/finch/internal/package.scala, core/src/test/scala/io/finch/BodySpec.scala, core/src/test/scala/io/finch/BootstrapSpec.scala, core/src/test/scala/io/finch/data/Foo.scala, core/src/test/scala/io/finch/internal/HttpMessageSpec.scala, examples/src/test/scala/io/finch/todo/TodoSpec.scala
This is addressing #967.
The easiest way of supporting 415 (UnsupportedMediaType) is to return a special (singleton) exception from `Decode.Dispatchable[CT, CNil]` (the very last decoder in the list) so we can later match on that within a derived service.
Here is the proposed behavior:
- By default (a standard `Bootstrap`), a body endpoint that sees an unknown media type will resolve into `Throw(Error.NotParsed)` (fail-fast) with an underlying cause of `Decode.UnsupportedMediaType`.
- A `Bootstrap` option `enableUnsupportedMediaType` (false by default), would turn those errors into 415 responses. Note the default response remains 400.
I'm not entirely in love with encoding this logic in a special exception but it seems a very natural way to implement it.  I'm eager to hear what people …
=> Support 415

build.sbt
minor modification to `build.sbt` which removes duplicated `javaOptions` from `benchmarks`
=> removes duplicate Xss and Xms options

build.sbt
adjusts `javaOptions` by bumping stack size to `2048K`
fixes #993
=> adjusts stack size to address OOM error when running tests

argonaut/src/main/scala/io/finch/argonaut/Decoders.scala, benchmarks/src/main/scala/io/finch/benchmarks.scala, benchmarks/src/main/scala/io/finch/data/Foo.scala, circe/src/main/scala/io/finch/circe/AccumulatingDecoders.scala, circe/src/main/scala/io/finch/circe/Decoders.scala, core/src/main/scala/io/finch/Decode.scala, core/src/main/scala/io/finch/DecodeEntity.scala, core/src/main/scala/io/finch/Endpoint.scala, core/src/main/scala/io/finch/EndpointResult.scala, core/src/main/scala/io/finch/endpoint/body.scala, core/src/main/scala/io/finch/endpoint/header.scala, core/src/main/scala/io/finch/endpoint/multipart.scala, core/src/main/scala/io/finch/endpoint/param.scala, core/src/test/scala/io/finch/BodySpec.scala, core/src/test/scala/io/finch/DecodeEntityLaws.scala, core/src/test/scala/io/finch/EndpointSpec.scala, core/src/test/scala/io/finch/EvaluatingEndpointLaws.scala, core/src/test/scala/io/finch/FinchSpec.scala, core/src/test/scala/io/finch/MissingInstances.scala, core/src/test/scala/io/finch/data/Foo.scala, json-test/src/main/scala/io/finch/test/JsonLaws.scala, refined/src/main/scala/io/finch/refined/package.scala, refined/src/test/scala/io/finch/refined/PredicateFailedSpec.scala
This is a WIP for https://github.com/finagle/finch/issues/989
```scala
[error] /Users/prayagupd/buybest/sc212/finch/core/src/test/scala/io/finch/DecodeEntityLaws.scala:20:32: No implicit view available from cats.laws.IsEq[Either[Throwable,A]] => org.scalacheck.Prop.
[error]     "roundTrip" -> Prop.forAll { (a: A) => roundTrip(a) }
[error] 
```
=> replace twitter.Try[A] with scala.Either[Throwable, A]

core/src/main/scala/io/finch/Endpoint.scala, core/src/main/scala/io/finch/EndpointResult.scala, core/src/main/scala/io/finch/endpoint/body.scala, core/src/main/scala/io/finch/endpoint/multipart.scala, core/src/main/scala/io/finch/endpoint/path.scala, iteratee/src/main/scala/io/finch/iteratee/package.scala
This PR gets rid of implicit conversion we had to go from `EndpointResult[Id, A]` to `EndpointResult[F, A]`. This type-casting is now happening explicitly either via pattern matching `_: NotMatched[F]` or via `NotMatched.apply[F]` method.
=> Model NotMatched result more explicitly

README.md, build.sbt
Switching artifact names to `finchx` (x for next?) so we can keep publishing normal Finch artifacts separately.
=> Switch artifact names to finchx

build.sbt, circe/src/test/scala/io/finch/circe/test/CirceSpec.scala, core/src/main/scala/io/finch/Endpoint.scala, core/src/test/scala/io/finch/ToResponseSpec.scala, json-test/src/main/scala/io/finch/test/AbstractJsonSpec.scala, version.sbt
- Drops iteratee-twitter dependency
- Bumps Finagle to 18.10
- Triggers a release.
=> Prepare a release 0.25

README.md
Just a small life quality improvement to point to https://index.scala-lang.org/finagle/finch/finch-core instead of maven search
=> Point to index.scala-lang.org with version badge

core/src/main/scala/io/finch/EndpointResult.scala
So it's more in the spirit of how other methods are implemented.
=> Move EndpointResult.isMatched to a base class

core/src/main/scala/io/finch/Endpoint.scala, core/src/main/scala/io/finch/EndpointModule.scala, core/src/test/scala/io/finch/EndpointSpec.scala
It does what you think it does.
```scala
import io.finch._, io.finch.catsEffect._
val e = get(pathEmpty) { Ok("foo") }  // matches GET /
```
=> Introduce pathEmpty

core/src/main/scala/io/finch/internal/DummyExecutionContext.scala, core/src/main/scala/io/finch/internal/Mapper.scala, core/src/main/scala/io/finch/internal/package.scala, core/src/test/scala/io/finch/MethodSpec.scala
=> Add syntax support for Scala & Twitter Futures in Mapper

core/src/main/scala/io/finch/Output.scala, core/src/main/scala/io/finch/ToResponse.scala, core/src/main/scala/io/finch/ToService.scala
There is new API that allows us to skip header validation for certain headers. While it's not generally safe to use, it's totally fine if we know headers are always valid (content-length, date, etc).
=> Use HeaderMap.setUnsafe when possible

core/src/main/scala/io/finch/EndpointResult.scala, examples/src/main/resources/todo/index.html, examples/src/main/resources/todo/main.js, examples/src/main/scala/io/finch/todo/App.scala, examples/src/main/scala/io/finch/todo/Main.scala, examples/src/main/scala/io/finch/todo/Todo.scala, examples/src/test/scala/io/finch/todo/TodoSpec.scala
I was playing around the idea of doing better job with our examples to make them more appealing. This PR adds an HTML frontend for a Finch app. It looks like this.
Additionally this:
- Introduces `Endpoint.resource` to serve static content (see #1017)
- Makes use of `Ref` instead of `synchronized`
- Adds `EndpointResult.output` as a syntax (it's a bummer variance doesn't give us another option; I will file a ticket - #1021)
Curious to hear what people think about this.
=> Refine TODO App example

docs/src/main/tut/user-guide.md
- should be "io.finch.error.NotPresent" instead of "io.finch.error.NotFound"
=> fix typo in user guide regarding io.finch.Error

core/src/main/scala/io/finch/Endpoint.scala, core/src/test/scala/io/finch/EndToEndSpec.scala, core/src/test/scala/io/finch/EndpointSpec.scala
`.handleErrorWith` doesn't re-raise the error if the partial function doesn't match, so it leads to `MatchError` exception pointing to `ToService.handler` in the `Future` from `Service`.
Users lose the information about the type of exception caused the original problem.
=> Use .recoverWith instead of .handleErrorWith

benchmarks/src/main/scala/io/finch/benchmarks.scala, core/src/main/scala/io/finch/Bootstrap.scala, core/src/main/scala/io/finch/ToService.scala, core/src/test/scala/io/finch/EndToEndSpec.scala
Use `shapeless.OrElse` to resolve implicit evidence of `CTH` being a Coproduct or return `DummyImplicit` otherwise. Then fold this structure into boolean value to understand if we need to negotiate on Content-Type.
#1041
=> Enable content negotiation automatically

core/src/main/scala/io/finch/EncodeStream.scala, core/src/main/scala/io/finch/Endpoint.scala, core/src/main/scala/io/finch/Input.scala, core/src/main/scala/io/finch/LiftReader.scala, core/src/main/scala/io/finch/ToResponse.scala, core/src/test/scala/io/finch/InputSpec.scala, core/src/test/scala/io/finch/data/Foo.scala, fs2/src/main/scala/io/finch/fs2/package.scala, iteratee/src/main/scala/io/finch/iteratee/package.scala
This to address #1038 as well as make it more pluggable to adopt new streaming libraries (eg FS2). The type-class name is inspired by what Sergey is doing in #1042. The new machinery allows us to reuse the same instances between `ToResponse` (when serving streaming content) and `Input.withStream` allowing users to created chunked requests for testing.
Here is how it looks and feels:
```scala
import io.finch._, io.finch.iteratee._, io.interatee.Enumerator, cats.effect.IO
val i = Input
.post("/")
.withStream[Text.Plain](Enumerator.enumerate[IO, String]("foo", "bar", "baz"))
```
Also possible to encode JSON (as you would imagine). This does the right thing and encodes ND (newline-delimited) JSON stream, reusing the same code that we use on the outbound path:
```scala
import io.finch._, …
```
=> Abstract over Stream type in the outbound path

circe/src/main/scala/io/finch/circe/Decoders.scala, core/src/main/scala/io/finch/EncodeStream.scala, core/src/main/scala/io/finch/Endpoint.scala, core/src/main/scala/io/finch/Input.scala, core/src/main/scala/io/finch/Output.scala, core/src/main/scala/io/finch/ToResponse.scala, core/src/main/scala/io/finch/ToService.scala, core/src/test/scala/io/finch/InputSpec.scala, core/src/test/scala/io/finch/MethodSpec.scala, core/src/test/scala/io/finch/OutputSpec.scala, core/src/test/scala/io/finch/StreamingLaws.scala, examples/src/main/scala/io/finch/iteratee/Main.scala, fs2/src/main/scala/io/finch/fs2/package.scala, iteratee/src/main/scala/io/finch/iteratee/package.scala
See #1057.
This refactors `ToResponse` so it returns `F[Response]`, instead of just `Response` to allow for in-band stream evaluation.
UPDATE:
Nothing concerning in the benchmark:
```
BEFORE:
[info] JsonBootstrapBenchmark.foos                                thrpt   10   28777.149 ± 1351.610   ops/s
[info] JsonBootstrapBenchmark.foos:·gc.alloc.rate.norm            thrpt   10  103896.055 ±    0.019    B/op
[success] Total time: 37 s, completed Jan 19, 2019 5:09:30 PM
AFTER:
[info] Benchmark                                                   Mode  Cnt       Score      Error   Units
[info] JsonBootstrapBenchmark.foos                                thrpt   10   29342.207 ± 1092.418   ops/s
[info] JsonBootstrapBenchmark.foos:·gc.alloc.rate.norm            thrpt   10  104088.054 ±    0.018 …
```
=> Do not run stream out of band

docs/src/main/tut/user-guide.md
Remove the `headerExists` and `paramExists` from the documentation.
=> Cleanup user-guide.md

core/src/main/scala/io/finch/Endpoint.scala, core/src/main/scala/io/finch/EndpointModule.scala, core/src/main/scala/io/finch/endpoint/body.scala, core/src/main/scala/io/finch/endpoint/cookie.scala, core/src/main/scala/io/finch/endpoint/endpoint.scala, core/src/main/scala/io/finch/endpoint/header.scala, core/src/main/scala/io/finch/endpoint/multipart.scala, core/src/main/scala/io/finch/endpoint/param.scala, core/src/main/scala/io/finch/endpoint/path.scala, core/src/main/scala/io/finch/internal/Mapper.scala, core/src/main/scala/io/finch/internal/ToAsync.scala, core/src/main/scala/io/finch/package.scala, core/src/test/scala/io/finch/EndpointSpec.scala, core/src/test/scala/io/finch/MethodSpec.scala, core/src/test/scala/io/finch/internal/ToEffectLaws.scala, examples/src/main/scala/io/finch/iteratee/Main.scala, fs2/src/main/scala/io/finch/fs2/package.scala, iteratee/src/main/scala/io/finch/iteratee/package.scala
- Replace `Effect` type class boundaries with the least powerful one wherever it's possible. Mostly with `Sync`/`Async`
- Introduce `Endpoint.transformF` for `F[A] => F[B]` transformation, similar to `Kleisli.mapF`
In combination, those two changes open very promising doors together with `Endpoint.Compiled[F]`.
As an example, there is no `Effect` instance for `StateT` monad but there is one available for `Async`. Shortly speaking, it allows to maintain state over the Kleisli compositions of compiled Endpoint, so it piggybacks on top of `F[_]`. Instead of abusing `Request.ctx` users would be able to pass and change some request local state using `State[F, State, ?]` as async type:
```scala
case class State(msg: String)
type ST[A] = StateT[IO, State, A]
val state: Endpoint[ST, State] = …
```
=> Least powerful type classes + Endpoint.transformF

build.sbt
circe-fs2 is 0.11.0 yet, but shouldn't be a problem
=> Update only circe-core to 0.11.1

core/src/test/scala/io/finch/StreamingLaws.scala, fs2/src/main/scala/io/finch/fs2/package.scala, fs2/src/test/scala/io/finch/fs2/Fs2StreamingSpec.scala
The `ConcurrentEffect` instances are prioritized higher.
This means users can benefit from cancellation when possible
without loss of generality.
@vkostyukov this is what I had in mind with providing both versions and prioritizing them. But I don't know how to test that cancellation actually works. Any ideas?
=> Fs2 EncodeStream for both ConcurrentEffect and Effect monads

core/src/test/scala/io/finch/MethodSpec.scala, fs2/src/test/scala/io/finch/fs2/Fs2StreamingSpec.scala, iteratee/src/test/scala/io/finch/iteratee/IterateeStreamingSpec.scala
Deprecated since scalatest 3.0.6
The drop-in replacement is `ScalaCheckDrivenPropertyChecks`.
=> Replace references to deprecated GeneratorDrivenPropertyChecks

core/src/main/scala/io/finch/Endpoint.scala, core/src/test/scala/io/finch/EndpointSpec.scala
Also deprecates `transformF` as `transform` is now available.
=> Removed deprecated transform

README.md
Sigma is now known as Merit (and is still using Finch!)
https://www.merits.com/blog/sigma-rebrands-as-merit
=> Change Sigma to Merit in Adopters list

core/src/main/scala/io/finch/Endpoint.scala, core/src/main/scala/io/finch/internal/Mapper.scala, core/src/test/scala/io/finch/EndpointSpec.scala
fix for #1138
Idea is catch every exception that may happen in function that provided to Endpoint#mapOutput from Mapper.
=> catch possible exceptions of mapOutputs function

build.sbt, project/plugins.sbt
Looks like we are still calling `http://dl.bintray.com/tpolecat/maven` but I'm not sure why.
=> Use HTTPS for more resolvers

circe/src/main/scala/io/finch/circe/CirceError.scala, circe/src/main/scala/io/finch/circe/Decoders.scala
The result is already of type `Either`.
Also simplify the implementation a bit.
The second commit adds a specialized `CirceError` type,
that forwards to `cats.Show` for printing the error message.
=> Remove an allocation of Either in decodeCirce

project/plugins.sbt
Seems like plugin API was changed. Encoded `build/credentials.sbt.enc` causes compilation failure
=> Rollback sbt-pgp update

core/src/main/scala/io/finch/Endpoint.scala, core/src/test/scala/io/finch/EndpointSpec.scala
It's equivalent to `List(endpoints: _*).foldK` but a bit more convenient.
=> Add Endpoint.coproduct for summing a list of endpoints

build.sbt, circe/src/main/scala/io/finch/circe/AccumulatingDecoders.scala, circe/src/main/scala/io/finch/circe/Encoders.scala, circe/src/main/scala/io/finch/circe/package.scala, circe/src/test/scala/io/finch/circe/test/CirceSpec.scala, core/src/main/scala/io/finch/Endpoint.scala, core/src/main/scala/io/finch/internal/Mapper.scala, core/src/test/scala/io/finch/FinchSpec.scala, core/src/test/scala/io/finch/ServerSentEventSpec.scala, core/src/test/scala/io/finch/StreamingLaws.scala, core/src/test/scala/io/finch/internal/TooFastStringSpec.scala, examples/src/test/scala/io/finch/todo/TodoSpec.scala, json-test/src/main/scala/io/finch/test/AbstractJsonSpec.scala, project/metals.sbt
Resolves #1202 by adding support for 2.13. We're also forced to drop support for 2.11 here because a number of dependencies that are not cross built for both. Big thanks to @sergeykolbasov for figuring the weird SAM issue that caused the Mapper to not get resolved in a bunch of cases.
Couple things about this PR:
- Introduces a bunch of warnings from Scalatest, I plan on cleaning these up in a separate PR
- I'd still like to investigate cleaning up the sbt settings, I really like how Odin is does it.
- Examples and docs cannot be cross built until Twitter Server is cross built for 2.13
=> Add Support for Scala 2.13 and drop support for Scala 2.11

.gitignore, build.sbt, docs/src/main/tut/best-practices.md, docs/src/main/tut/contributing.md, docs/src/main/tut/cookbook.md, docs/src/main/tut/index.md, docs/src/main/tut/user-guide.md, project/metals.sbt, project/plugins.sbt
Our microsite build has been broken and outdated while we've been moving to an Effect Agnostic `Endpoint`. This PR fixes the `sbt docs/makeMicrosite` command. The code examples in the docs all compile but the text that surrounds them is still out of date. My current thinking is that we can use this as a base to fix the text, although I'm open to alternative approaches to fixing our docs. If we decide to merge this, I don't think we should publish the docs to the website until all the text has been fixed.
Some things to note / questions:
- I replaced the Server Sent Event example's use of `AsyncStream` with `Fs2`
- The latest sbt-microsites seems to replace favicons and icons with its own. I've noticed this on other microsites like [cats effect](https://typelevel.org/cats-effect/).
- Set …
=> Fix microsite compile

docs/mdoc/user-guide.md
Add a few examples to the user guide docs and remove the mentions about futures so that it is a bit closer to what's actually in finchx.
Also add a link to giter8 template to the index.
=> user-guide.md: add a few examples and remove mentions about futures

README.md
Maybe, server finish running before receiving a request, not exist `Await.ready`
=> modified the document of sample code (in README).

.scala-steward.conf, build.sbt
chore: use circe version for circe-fs2
---
**Motivation:**
Must be aligned
chore: add scala steward configuration
---
**Modification:**
* freeze `cats-effect` to major version 2
* freeze `fs2-core` to major version (next use CE3)
* freeze `circe-fs2` to minor version (next use fs2 > v3)
=> Scala steward configuration

build/build.sh
A few alternatives are also discussed here: https://stackoverflow.com/questions/61096521/how-to-use-gpg-key-in-github-actions
=> Maybe move gpg keys under .gnupg folder

README.md, build.sbt
Looks like we said [Finch 0.32.1](https://github.com/finagle/finch/releases/tag/v0.32.1) was the last release where we publish both artifacts. I don't think we actually published the legacy (Twitter Future) artifacts back then so I say we just rename artifacts now and publish one more release.
=> Rename artifacts finchx to finch

core/src/test/scala/io/finch/FinchSpec.scala, core/src/test/scala/io/finch/ServerSentEventSpec.scala, docs/mdoc/cookbook.md, docs/mdoc/user-guide.md
The arb instances aren't used by any tests, and the docs are a
confusing fabrication.
=> Remove dead references to AsyncStream

build.sbt
**Motivation:**
Trigger scalafix and scalafmt on compile
**Modification:**
* validate should check formatting before compiling (as compile now trigger formatting)
* disable format on compile when on CI environment
=> chore: format on compile

build.sbt, json-test/src/main/scala/io/finch/test/AbstractJsonSpec.scala, json-test/src/main/scala/io/finch/test/JsonLaws.scala
Scala 2.12.16 and 2.13.9 will prohibit the use of `?` in this way, so this changes to the newer `*` syntax which will also work in Scala 3
=> kind-projector 0.13.2 (was 0.10.3)

benchmarks/src/main/scala/io/finch/benchmarks.scala, core/src/main/scala/io/finch/Bootstrap.scala, core/src/main/scala/io/finch/Endpoint.scala, core/src/main/scala/io/finch/endpoint/endpoint.scala, core/src/test/scala/io/finch/BootstrapSpec.scala, core/src/test/scala/io/finch/EndToEndSpec.scala, examples/src/main/scala/io/finch/div/Main.scala, examples/src/main/scala/io/finch/iteratee/Main.scala, examples/src/main/scala/io/finch/middleware/Main.scala, examples/src/main/scala/io/finch/todo/App.scala, examples/src/main/scala/io/finch/todo/Main.scala, examples/src/main/scala/io/finch/wrk/Finagle.scala, examples/src/main/scala/io/finch/wrk/Finch.scala, examples/src/main/scala/io/finch/wrk/Wrk.scala
We can just use IO.delay and avoid dealing with TwitterFuture to IO conversions.
=> Clean up examples to not use toAsync

core/src/main/scala/io/finch/Accept.scala, core/src/main/scala/io/finch/Bootstrap.scala, core/src/main/scala/io/finch/Compile.scala, core/src/main/scala/io/finch/Output.scala, core/src/main/scala/io/finch/ToResponse.scala, core/src/test/scala/io/finch/EndToEndSpec.scala
Controlled by a flag in `Bootstrap` similar to other response codes.
Returns 406 when enabled and no matching Accept header is found.
Refactors `ToResponse.Negotiable` to achieve this effect:
- Value and exception encoders are now bundled into `Negotiated`
- `Negotiated` also includes an `acceptable` flag
Closes #1147 in favour of the preferred approach discussed in that PR
=> Add support for 406 Not Acceptable response on content negotiation

build.sbt, project/plugins.sbt
- Replace deprecated `sonatypeRepo` resolver with `sonatypeOssRepos`
- Ensure file source and writer are closed
- Exclude `siteSubdirName` from lint keys to suppress warning
- Update `joda-time` dependency
=> Cleanup build

core/src/main/scala/io/finch/Endpoint.scala, core/src/main/scala/io/finch/Error.scala, core/src/test/scala/io/finch/EndpointSpec.scala
Closes #808 - I didn't add the `validated` method, because it's nothing more than `mapAsync(validator(_).liftTo[F])` now that we have removed `RequestItem`
=> Migrate Errors to NonEmptyChain and add a Semigroup instance

circe/src/main/scala/io/finch/circe/AccumulatingDecoders.scala, circe/src/main/scala/io/finch/circe/Decoders.scala, core/src/main/scala/io/finch/Compile.scala, core/src/main/scala/io/finch/Endpoint.scala, core/src/main/scala/io/finch/internal/Mapper.scala
Also add `Endpoint.output` constructor and reuse it.
Convert some instances to SAM syntax.
=> Use ApplicativeThrow and MonadThrow type aliases

build.sbt, circe/src/test/scala/io/finch/circe/test/CirceSpec.scala, core/src/main/scala/io/finch/DecodeEntity.scala, core/src/main/scala/io/finch/Error.scala, core/src/main/scala/io/finch/endpoint/multipart.scala, core/src/main/scala/io/finch/endpoint/param.scala, core/src/test/scala/io/finch/BodySpec.scala, core/src/test/scala/io/finch/BootstrapSpec.scala, core/src/test/scala/io/finch/EndpointSpec.scala, core/src/test/scala/io/finch/FinchSpec.scala, examples/src/main/scala/io/finch/iteratee/Main.scala, json-test/src/main/scala/io/finch/test/JsonLaws.scala, refined/src/main/scala/io/finch/refined/package.scala, refined/src/test/scala/io/finch/refined/PredicateFailedSpec.scala
- Replace usage of deprecated methods
- Use ScalaTest `inside` instead of inexhaustive pattern matching
=> Enable fatal warnings and set Scala 2.13 as default

README.md
Seems that after the `0.34.0` release some things have changed, but they are not reflected in the examples.
There is a https://github.com/finagle/finch/issues/1254, but it seems to be opened for a different root cause. But it can be closed after the merge
=> Update Hello World example
